### ISSUE TITLE
continueAfterRatelimitError set to true but still getting ratelimit exceptions

### ISSUE THREAD

**Issue by Woolfe** [not-an-aardvark/snoowrap#105]
Here's my config code:

```
const Snoowrap = require('snoowrap');
const Snoostorm = require('snoostorm');

const r = new Snoowrap({
    userAgent: '***',
    clientId: '***',
    clientSecret: '***',
    username: '***',
    password: '***'

});

r.config({ continueAfterRatelimitError: true });
const client = new Snoostorm(r);

const streamOpts = {
    subreddit: 'testingground4bots',
    results: 25
};

const comments = client.CommentStream(streamOpts);
comments.on('comment', (comment) => {
    //some logic deciding if to reply and if so, the content of the reply
    comment.reply('foo');
});
```

When my bot replies to comments before the rate limit expires, I get "Unhandled rejection Error: RATELIMIT,you are doing that too much. try again in 9 minutes". Am I missing something obvious here? From the docs it seems like this should requeue the attempted reply and throw no error.

I'm using Node v8.1.4

**Comment by not-an-aardvark** [comment]
Thanks for the report.

There are two "ratelimits" at play here. The first is a general OAuth ratelimit of 600 API requests every 10 minutes for all API users. The second is a ratelimit on submitting content (posts/comments/PMs/etc.) that reddit imposes on new accounts and accounts with low karma, regardless of whether they're using the API.

snoowrap only guards against the API ratelimit, but it doesn't handle other content-creation limits that reddit might impose. To get around those issues, one option would be to get more karma on the account that you're using.

**Comment by gkiely** [comment]
@not-an-aardvark I'm currently running into this same issue for submits.

It would be cool if there was a way parse the rate limit error/queue submits with snoowrap.
