### ISSUE TITLE
Cannot read property prototype of undefined (fromAuthCode)

### ISSUE THREAD

**Issue by AlexChesters** [not-an-aardvark/snoowrap#106]
I'm getting an exception when calling `fromAuthCode` like below:
```javascript
import { fromAuthCode } from 'snoowrap'

export const authenticate = (code) => {
  return (dispatch) => {
    const options = {
      code,
      clientId: MY_CLIENT_ID,
      scope: ['read'],
      redirectUri: 'http://localhost:8081/authenticate'
    }
    fromAuthCode(options).then((r) => {
      r.getHot().map(post => post.title).then(console.log)
    })
  }
}
```

However I'm getting the following error in Chrome and Firefox
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
```
Which is being thrown from [this line](https://github.com/not-an-aardvark/snoowrap/blob/a38b53fa32f541331008ed9237baf7b5d49411d9/src/snoowrap.js#L215).

Some more information:
* I'm using `webpack` as a bundler and running locally using `webpack-dev-server`
* I'm using `babel` to transpile

Any ideas?

**Comment by AlexChesters** [comment]
I've done a bit of digging and found something interesting.
This doesn't work
```javascript
import { fromAuthCode } from 'snoowrap'

fromAuthCode(options).then((r) => {
  r.getHot().map(post => post.title).then(console.log)
})
```
This does (albeit with a 401 error from the access token endpoint)
```javascript
window.snoowrap.fromAuthCode(options).then((r) => {
  r.getHot().map(post => post.title).then(console.log)
})
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. This is working as intended -- `snoowrap.fromAuthCode` depends on the `this` value being a snoowrap constructor, so you need to call it as `snoowrap.fromAuthCode` -- you can't call `fromAuthCode` on its own.

**Comment by AlexChesters** [comment]
Ah I see. Fantastic, thanks for your help! :)
