### ISSUE TITLE
Undefined `btoa` function causes reference errors

### ISSUE THREAD

**Issue by doppio** [not-an-aardvark/snoowrap#109]
When using `reddit.getComment(commentId).fetch()` in a Node environment, I get the following error:
```
ReferenceError: btoa is not defined
    at snoowrap.rawRequest (<project_dir>/node_modules/snoowrap/dist/xhr.js:58:110)
    at snoowrap.credentialedClientRequest (<project_dir>/node_modules/snoowrap/dist/request_handler.js:187:48)
    at snoowrap.updateAccessToken (<project_dir>/node_modules/snoowrap/dist/request_handler.js:225:17)
```

I've tried running various versions of snoowrap (including the latest 3) and several versions of Node. Currently I'm on Node v7.10.0.

I don't see where `btoa` is defined. This seems like a bug, but maybe I'm doing something wrong here?

**Comment by not-an-aardvark** [comment]
Thanks for the report. The `xhr.js` file should only get used if snoowrap is running in a browser environment. This check works by [testing for the existence of the `XMLHttpRequest` global](https://github.com/not-an-aardvark/snoowrap/blob/e62cd662ce11ca691ed175d1f3b96709015e0614/src/request_handler.js#L286).

Do you have a `XMLHttpRequest` global present in Node for some reason?

**Comment by doppio** [comment]
Thanks for the fast response! Strangely, another dependency in my project seems to be defining it as a global:
```XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;```

I should be able to work around it, but I wonder if it would also make sense for snoowrap to check something like `typeof process !== 'undefined'` to be more certain about its environment?

**Comment by not-an-aardvark** [comment]
Would that actually be better? It seems like someone could just override the global `process` variable too?

**Comment by doppio** [comment]
That's fair. Maybe I ought to suggest that the other library not just dump XMLHttpRequest into the global namespace. Seems like this is more of an issue with that library than with snoowrap after all. Thanks for helping me investigate!
