### ISSUE TITLE
Promise Chain Rejection

### ISSUE THREAD

**Issue by kennymuli** [not-an-aardvark/snoowrap#110]
I'm trying to get messages and then mark them as read. The category of the messages I'm testing out are under the subject of "user mention" mostly.

I try with the command
`r.getMessage(ID).markAsRead();`

The response is 
`Unhandled rejection StatusCodeError: 400 - {"message":"Bad Request","error":400}`

When I just run r.getMessage(ID) it returns
`Private Message { name: REDACTED };`

Here is my snoowrap setup:
`
const r = new snoowrap({ 
	userAgent:'App',
	clientId:'REDACTED',
	clientSecret:'REDACTED',
	username:'REDACTED',
	password:'REDACTED'
});
`

**Comment by kennymuli** [comment]
Okay I caught the error, I can't mark a user mention as read, only private messages. Is there any way to mark user mentions as read?

**Comment by not-an-aardvark** [comment]
No, I don't know of a way to do this.
