### ISSUE TITLE
Support for profile page/user subreddit (currently in beta)?

### ISSUE THREAD

**Issue by Fraasi** [not-an-aardvark/snoowrap#111]
There's a new profile page thing coming in reddit, which seems quite perfect for some bots, as it doesn't require you to open a new subreddit for your bot to have it's own home.
[explanation and examples](https://www.reddit.com/r/announcements/comments/60p3n1/tldr_today_were_testing_out_a_new_feature_that/)

Maybe somebody knows a workaround for snoowrap to post to these 'user subreddits', or is it maybe already in developement?

**Comment by not-an-aardvark** [comment]
You can use a user subreddit in the same way as a regular subreddit by prepending `u_` to the username.

For example, to get info about the subreddit at https://www.reddit.com/user/kn0thing, you can use `r.getSubreddit('u_kn0thing')`.

**Comment by Fraasi** [comment]
Thank you! Works perfectly. I tried u/kn0thing and whatnot but not underscore...
