### ISSUE TITLE
Search: Difficulty getting snoowrap search to match reddit results

### ISSUE THREAD

**Issue by ronnyli** [not-an-aardvark/snoowrap#112]
For the following URL search of a sleeping kitten `url:imgur.com/hyLlADL`, reddit returns several submissions ([link](https://www.reddit.com/search?q=url%3Aimgur.com%2FhyLlADL&restrict_sr=&sort=relevance&t=all)) but the same query in snoowrap has zero results. Is there anything obvious that I'm missing? Thanks in advance!

![22292008_10156656904593294_1741289361_n](https://user-images.githubusercontent.com/6841011/31260797-679f4cd2-aa1e-11e7-8cfc-82639ecc644d.png)

**Comment by not-an-aardvark** [comment]
I think reddit defaults to `lucene` search syntax, not `plain`.

**Comment by ronnyli** [comment]
Thank you for the fast response and the simple solution. It works now!
