### ISSUE TITLE
Is it possible to search Reddit submissions without authentication?

### ISSUE THREAD

**Issue by ronnyli** [not-an-aardvark/snoowrap#114]
It seems like it's not required when calling the Reddit API normally so I was just curious if the same behavior would be in snoowrap. Thanks in advance!

Example:
`https://api.reddit.com/submit.api?url=imgur.com/hyLlADL`

**Comment by not-an-aardvark** [comment]
Hi,

No, it's not currently possible to do that with snoowrap -- I think the only "official" way to programmatically access reddit is through the OAuth API. That said, it should be possible to use [Application Only OAuth](https://github.com/reddit/reddit/wiki/oauth2#application-only-oauth) to get an access token, and create a snoowrap instance from the access token. ([reddit-oauth-helper](https://not-an-aardvark.github.io/reddit-oauth-helper/) does this to generate its "anonymous token" -- you can see the source code [here](https://github.com/not-an-aardvark/reddit-oauth-helper/blob/f090f954322cdbf4e388132ec8659afa1cdf0ecd/browser.jsx#L80-L98).)
