### ISSUE TITLE
Specifying 'Options for the resulting Listing'.

### ISSUE THREAD

**Issue by Tvde1** [not-an-aardvark/snoowrap#116]
I was looking at the docs of `RedditUser` and I wanted to fetch all comments below a certain karma.  
The docs say you can supply an `options` parameter to `getComments()` (and many more functions).

Where do I find what I can put in these options?

**Comment by not-an-aardvark** [comment]
See [here](https://not-an-aardvark.github.io/snoowrap/Listing.html)
