### ISSUE TITLE
Can someone help me on creating a new instance of snoowwrap? [help wanted]

### ISSUE THREAD

**Issue by gabrieldi95** [not-an-aardvark/snoowrap#119]
I mean, I don't know what should I put in the object.
const r = new snoowrap({
  
 userAgent: 'put your user-agent string here',

  clientId: 'put your client id here',

  clientSecret: 'put your client secret here',
  
  #refreshToken: 'put your refresh token here'
});

**Comment by not-an-aardvark** [comment]
Hi,

See the [documentation](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#snoowrap__anchor) for more info about those properties. The [reddit OAuth documentation](https://github.com/reddit/reddit/wiki/oauth2) could also be useful.
