### ISSUE TITLE
Is there a way to get a list of the Top x subReddits?

### ISSUE THREAD

**Issue by gabrieldi95** [not-an-aardvark/snoowrap#120]

**Comment by not-an-aardvark** [comment]
Does [`getPopularSubreddits`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#getPopularSubreddits__anchor) do what you need?

**Comment by gabrieldi95** [comment]
Yes, thank you

**Comment by not-an-aardvark** [comment]
No problem.
