### ISSUE TITLE
Passing a readable stream into uploadStylesheetImage method

### ISSUE THREAD

**Issue by emyarod** [not-an-aardvark/snoowrap#122]
I am trying to upload images in an archive as readable streams but keep receiving error 500s back in reddit's response. Am I incorrectly using the `uploadStylesheetImage` method? As an alternative, I am currently uncompressing the images into a temp directory then removing that directory after the file uploads are complete. How would I stream the images from the archive to the `uploadStylesheetImage` method?

```js
const restoreStylesheetImage = (r, subreddit, stylesheetImage) => {
  const [name, imageType] = stylesheetImage.name.split('.');
  const strim = new stream.PassThrough();
  strim.end(stylesheetImage.data); // stylesheetImage.data is an image as type Node.js Buffer

  r
    .getSubreddit(subreddit)
    .uploadStylesheetImage({
      name,
      imageType,
      file: strim,
    })
    .catch(console.error);
};
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. It looks like this is caused by https://github.com/request/request/issues/2499.

You could try the workaround described in https://github.com/form-data/form-data/issues/356#issue-234978025, although it doesn't seem like an ideal solution.

**Comment by emyarod** [comment]
I see, thank you for the explanation. I will look into the workaround in the links you provided

**Comment by not-an-aardvark** [comment]
Well, you could probably accumulate the stream into a buffer, and then use the workaround to send the buffer (which would have known length at that point). That does lose some of the advantages of using a stream, but it will probably be faster than writing to the filesystem, and it won't leave files around if something crashes.

**Comment by SpyTec** [comment]
Since the solution proposed by not-an-aardvark seems to work I'm going to go ahead and close this due to inactivity. If you want to reopen the ticket just make a comment and I'll open it.
