### ISSUE TITLE
Best way to catch StatusCodeError: 503

### ISSUE THREAD

**Issue by shredding** [not-an-aardvark/snoowrap#123]
I occasionally receive `Unhandled rejection StatusCodeError: 503` in my code when `maxRetryAttempts` fails.

I now wonder how to attack that at best. I have a lot of potential failure points (basically everytime i make an api call) and wonder if there is a catch-all solution to this (i just want to log the origin and call it a day, as the stuff gets worked out on the next run).

**Comment by not-an-aardvark** [comment]
You could do something like

```js
r.getNew('redditdev')
    .catch({statusCode: 503}, err => {
        console.error(`something bad happened: ${err.message}`);
    });
```

It's not possible to add this as a global handler -- you would need to add it for each error that you want to log.

**Comment by shredding** [comment]
Thanks for the reply.

I solved it like that:

https://github.com/shredding/stellar-bot/blob/master/src/adapters/reddit.js#L23-L31
