### ISSUE TITLE
Cannot delete subreddit images

### ISSUE THREAD

**Issue by emyarod** [not-an-aardvark/snoowrap#125]
When attempting to delete any subreddit images, the return value is always a 404 Error. Am I incorrectly feeding in the image name, or is there an issue elsewhere?

```js
r
    .getSubreddit(subreddit)
    .deleteImage({ imageName: 'spritesheet' })
    .catch(console.error);
```

**Comment by not-an-aardvark** [comment]
Can you add `r.config({debug: true});` to your code and paste the output?

**Comment by emyarod** [comment]
this is what I got

```
[debug] Received a 404 status code from a `post` request sent to https://oauth.reddit.com/r/subreddit/api/delete_sr_image?raw_json=1. ratelimitRemaining: 599
```

**Comment by not-an-aardvark** [comment]
Fixed, thanks for reporting.
