### ISSUE TITLE
Subreddit `.editSettings()` unable to modify subreddit visibility

### ISSUE THREAD

**Issue by emyarod** [not-an-aardvark/snoowrap#126]
I am attempting to modify the visibility of a subreddit, but the visibility change is not made:

```js
r.getSubreddit(subreddit).editSettings({ type: 'public' });
```

I am using a permanent refresh token to authenticate as a subreddit moderator with the relevant permissions enabled.

Here is the debug output:

```
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/subreddit/about?raw_json=1. ratelimitRemaining: 559
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/subreddit/about/edit?raw_json=1. ratelimitRemaining: 558
[debug] Received a 200 status code from a `post` request sent to https://oauth.reddit.com/api/site_admin?raw_json=1. ratelimitRemaining: 557
```

**Comment by not-an-aardvark** [comment]
Fixed, thanks for reporting.

**Comment by emyarod** [comment]
@not-an-aardvark when I try to pass the result from `subredditA.getSettings()` into `subredditB.editSettings(subredditA_settings)`, the subreddit visibility remains unchanged. I can work around this on my end, by adding a `type` key to my `settings.json` and using the value from `subreddit_type`, but would it be possible to just be able to pass around the return value of `subredditA.getSettings()`?

**Comment by not-an-aardvark** [comment]
This is basically an inconsistency in reddit's API (the GET endpoint returns a `subreddit_type` key, but the POST endpoint expects a `type` key). In theory I suppose snoowrap could also accept a `subreddit_type` key on `editSettings`, but it currently does not.

**Comment by emyarod** [comment]
I see. Thank you for the quick fixes and explanation!
