### ISSUE TITLE
Get Posts Of Auto Moderator

### ISSUE THREAD

**Issue by matthias-herrmann** [not-an-aardvark/snoowrap#127]
Idk if this is a feature request or whether this can be done already:
Is there a way to get posts in a subreddit submitted by the AutoModerator? e.g. Daily general discussions

Currently my temporary solution looks like this: 
```
async function getDailyPost() { 
    let subreddit = await r.getSubreddit('ArkEcosystem');
    let dailyPost = await subreddit.getHot()
                                   .find((post) => 
                                   {
                                       let lowerTitle = post.title.toLowerCase();
                                       return post.author.name === 'AutoModerator' && lowerTitle.indexOf('daily general discussion') !== -1;
                                   });
}
```

**Comment by not-an-aardvark** [comment]
That looks like the right way to do it. If the post is stickied, you can also use [`getSticky`](https://not-an-aardvark.github.io/snoowrap/Subreddit.html#getSticky__anchor). Another option would be to use [`search`](https://not-an-aardvark.github.io/snoowrap/Subreddit.html#search__anchor) for something like `author:AutoModerator`.
