### ISSUE TITLE
How to use Expand Replies

### ISSUE THREAD

**Issue by nimwijetunga** [not-an-aardvark/snoowrap#133]
Once I get my new object tree how can I enumerate through it to get the individual fields (such as body, upvotes, downvotes, etc..)?

**Comment by not-an-aardvark** [comment]
Can you give more details about what you're doing? I don't understand the question.

**Comment by nimwijetunga** [comment]
When using the expand replies command what type of object is returned and how can I traverse through it. An example would be highly beneficial, thanks!

**Comment by not-an-aardvark** [comment]
I think `expandReplies` returns a new version of the Submission object, where the `comments` field contains a list of all of the top-level comments that were found.

**Comment by not-an-aardvark** [comment]
Closing because the question has been answered; feel free to continue the discussion if you have any more questions.
