### ISSUE TITLE
Documentation for properties of classes

### ISSUE THREAD

**Issue by froehlichA** [not-an-aardvark/snoowrap#135]
The docs contain all methods available, but not the properties.

For example, the docs say to retrieve a specific submission with the command:
```js 
r.getSubmission('2np694')
```
However, there is no documentation about how to retrieve the title, score or upvote ratio of the submission.

**Comment by not-an-aardvark** [comment]
Thanks for the report. However, this is intentional -- the properties are pulled directly from reddit, and snoowrap has no control over them. The list of properties could change or expand arbitrarily if something changes on reddit's backend, so any documentation on them would frequently become inaccurate.

**Comment by froehlichA** [comment]
Is there any documentation by reddit, then? I can't seem to find anything.

**Comment by not-an-aardvark** [comment]
Not that I'm aware of. My recommendation would be to either `console.log` the object that you're examining to access its properties, or visit the corresponding URL in your browser (with `.json` at the end to view the JSON version).

**Comment by DavidSampson** [comment]
Can this be reopened? The Typescript type definitions include the properties, why not use those to feed the documentation?

**Comment by SpyTec** [comment]
> 
> 
> Can this be reopened? The Typescript type definitions include the properties, why not use those to feed the documentation?

No, your issue is for something else so please open a new issue for it. TypeScript definitions do not have the same verbosity for documentation as our JSDoc currently have
