### ISSUE TITLE
Search API time Question

### ISSUE THREAD

**Issue by drelei** [not-an-aardvark/snoowrap#137]
What is the best way to get all posts within a time period like 01/01/2016 00:00:00 to 01/01/2017 00:00:00?

I saw the search API and didn't see the options listed for `before`, `after`, `start`, `end`, or similar.

`r.getSubreddit('snoowrap').search({sort: 'year'}).then(console.log)`

Thank you

**Comment by not-an-aardvark** [comment]
Due to [changes in the search API](https://www.reddit.com/r/changelog/comments/7tus5f/update_to_search_api/), this is no longer possible.
