### ISSUE TITLE
Get search URL

### ISSUE THREAD

**Issue by garyking** [not-an-aardvark/snoowrap#138]
Is it possible to perform a search, and in the `then()` method, get the URL of the search results?

**Comment by not-an-aardvark** [comment]
No, I don't think so. Could you elaborate on why you want to do that?

**Comment by garyking** [comment]
I'm writing a Node CLI script that accepts user input, searches Reddit for it, then opens the most relevant post for it in the default browser. If no result is found, then I want to open the Reddit search results URL instead, so that the user can modify the search result, etc.

**Comment by not-an-aardvark** [comment]
Thanks for clarifying. It's not possible to get a URL like that from snoowrap, but if you have all the parameters (subreddit, query, etc.) it should be fairly simple to build a URL yourself.
