### ISSUE TITLE
Get Private Messages?

### ISSUE THREAD

**Issue by MayorMonty** [not-an-aardvark/snoowrap#146]
I've been looking through the document, and while it appears to be able to get a private message by ID, there appears to be no way to get all the private messages of the currently authenticated user. Am I missing something?

Thanks!

**Comment by not-an-aardvark** [comment]
Hi, have you tried [`getInbox`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#getInbox__anchor)?

**Comment by MayorMonty** [comment]
Oh, I'm sorry! I didn't even see the methods documented in the snoowrap page! Apologies for wasting your time!
