### ISSUE TITLE
TypeError: tokenInfo.scope is undefined

### ISSUE THREAD

**Issue by nexequ** [not-an-aardvark/snoowrap#149]
const config = {
	  client_id: process.env.client_id,
	  client_secret: process.env.client_secret,
	  username: process.env.username,
	  password: process.env.password,
	  user_agent: 'Agent'
    };
    r = new snoowrap(config);

With that configuration I've got:
TypeError: tokenInfo.scope is undefined.

Event when I tried:

    const config = {
	    client_id: process.env.client_id,
	    client_secret: process.env.client_secret,
	    username: process.env.username,
	    password: process.env.password,
	    user_agent: 'Agent',
            scope: ['history'] // added that
    };

It doesn't work and the error is the same. How to get work with snoowrap then?

**Comment by not-an-aardvark** [comment]
Hi,

Could you show the rest of your code? I don't think a `tokenInfo.scope` error would be occurring from just the code you've given.

**Comment by nexequ** [comment]
I've also tried snoowrap code and:

    function updateAccessToken() {
       alert(_this2.scope) // here it is null
      _this2.scope = tokenInfo.scope.split(' ');
    }

**Comment by not-an-aardvark** [comment]
This looks like the same issue as https://github.com/not-an-aardvark/snoowrap/issues/93. Is your app a "personal script"?

**Comment by nexequ** [comment]
Actually it is web application. Can you add that in updateAccessToken():

    if (tokenInfo.error === 'unauthorized_client') {
      throw new Error('Only script apps may use password auth');
    }



{error_description: "Only script apps may use password auth", error: "unauthorized_client"}
