### ISSUE TITLE
Get edited comments? [Question]

### ISSUE THREAD

**Issue by mhd3v** [not-an-aardvark/snoowrap#152]
Hey, is there a way I can get only the comments that were edited? I've looked through the code, but I can't seem to find anything like this. The edited boolean in each comment object is kinda useless, since getNewComments is only getting new comments each time. If anyone would direct me in the right direction, I would be very grateful.

**Comment by SM-Wistful** [comment]
It's possible, but you need to be a [moderator of the subreddit](https://www.reddit.com/r/modnews/comments/2dgmd4/moderators_edited_page_now_available_at/).

**Comment by SpyTec** [comment]
It's something we can implement. There is an `/about/edited` as Sam pointed out. This will return all edited items, posts and comments alike, from the feed. Though you need to be a moderator or it will throw a 404 or 403
