### ISSUE TITLE
Add config settings

### ISSUE THREAD

**Issue by dessalines** [not-an-aardvark/snoowrap#156]
This whole library didn't work effectively without adding : 
```ts
snooWrapOptions: snoowrap.ConfigOptions = {
    continueAfterRatelimitError: true,
    requestDelay: this.waitMS
  }
this.r.config(this.snooWrapOptions);
```

**Comment by not-an-aardvark** [comment]
Thanks for creating an issue. I don't understand what you're proposing -- snoowrap already has [config settings](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#config__anchor), which you seem to have found given that you're using them. Could you elaborate on what you mean?

**Comment by dessalines** [comment]
Sorry, I meant to add this to the readme.

**Comment by not-an-aardvark** [comment]
Sure, I'd be fine with adding these to the readme. Feel free to create a pull request if you're still interested in adding this.
