### ISSUE TITLE
Get subscriber count for Subreddit

### ISSUE THREAD

**Issue by garyking** [not-an-aardvark/snoowrap#158]
Please make it possible to get the subscriber count for a Subreddit. This can be done via the `/r/subreddit/about` endpoint.

**Comment by not-an-aardvark** [comment]
Hi, thanks for reporting an issue.

This already exists -- it can already be done with `r.getSubreddit('subreddit_name').fetch().then(response => response.active_user_count)`.

**Comment by garyking** [comment]
Thanks I see it now.
