### ISSUE TITLE
listing.map isn't a function

### ISSUE THREAD

**Issue by Bananeh** [not-an-aardvark/snoowrap#159]
`
r.getHot(subreddit).then(listing => {
subredditPost = (listing.map(submission => submission.url)) 
                message.channel.send(subredditPost[Math.floor(Math.random() * subredditPost.length)]);
        });
`

This code was working fine earlier today. I was trying to get a random selection from an array of the hot posts from a subreddit. The error is "listing.map is not a function". I am super confused about this.

If it matters, the message.channel.send is from discord.js. I am using this for a discord bot.

**Comment by not-an-aardvark** [comment]
Sorry, I'm not sure what's going on here. I can't reproduce the issue using the code that you've provided. I'd recommend double-checking your code to make sure everything else is doing what you'd expect (e.g. printing `listing` to make sure it's actually a listing).

If you're still not sure what's going on I'd recommend posting the full code on `/r/redditdev`.
