### ISSUE TITLE
How to manually walk through listing pages

### ISSUE THREAD

**Issue by page6de** [not-an-aardvark/snoowrap#160]
I am using snoowrap in a Backend Service, where I want to fetch page after page. Because it is a stateless service, I need to create a new instance on every request. That way, I have no clue how to manually fetch the pages one after another, because I can not use a listing from a previous request and call fetchMore on hat instance. 
So is there a way to get the listings after-property and and pass it to the next listing call?

**Comment by not-an-aardvark** [comment]
No, there isn't an officially supported way to do this.
