### ISSUE TITLE
search fetchAll returns too little results

### ISSUE THREAD

**Issue by AAverin** [not-an-aardvark/snoowrap#162]
Both
`r.search({ query: "site:amazon.com", time: "week", sort: "new" }).fetchAll()`
and
`r.search({ query: "site:amazon.com", time: "month", sort: "new" }).fetchAll()`
return 244-245 results

How can I get the rest? According to documentation `fetchAll()` is supposed to return all available results

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue. Are you able to get more than this many results using reddit's UI? Reddit has limits on the number of posts it will return, so it might be that only 244-245 posts are available from the API. (Usually the limit is closer to 1000, although it can vary depending on whether some posts are removed.)

**Comment by AAverin** [comment]
@not-an-aardvark 
Hmm, you're right, in the UI I can also see up to 220-250 posts.
Is this a hard limit from the reddit side? Is it possible to go below this limit somehow?

**Comment by not-an-aardvark** [comment]
It's not possible to go past this limit by using reddit's API. I think there are some third-party services like [Pushshift](https://pushshift.io/) that archive posts and might offer that functionality, but I haven't tried them out myself.

**Comment by AAverin** [comment]
Thanks for clarification
