### ISSUE TITLE
Need a method to get a batch of submissions via list of IDs

### ISSUE THREAD

**Issue by exzizt** [not-an-aardvark/snoowrap#164]
This would be a great feature. Currently, I believe you can only get one submission at a time, which isn't nice because of the 60 requests per minute limit.

You can get a list of two submissions via a URL like this, for example: https://api.reddit.com/by_id/t3_9l9vof,t3_9la341.json

Why not implement this in the API?

**Comment by SpyTec** [comment]
You should be able to extend Snoowrap and utilize [rawRequest](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#rawRequest__anchor) to go around this.

I'm not sure what would be the best way to implement this on snoowrap, @not-an-aardvark might have an idea. If I understand the code correctly you should be able to utilize [`_getListing()`](https://github.com/not-an-aardvark/snoowrap/blob/master/src/snoowrap.js#L1450-L1471) in snoowrap.js with a function called something like `getListings()`

**Comment by krrishdholakia** [comment]
Hey, I'm trying to do :
`r.getContentByIds(['clc2f4','t3_9la341']).then(console.log);`

But I'm getting a: 

TypeError: r.getContentByIds is not a function

Is this not available yet?

**Comment by SpyTec** [comment]
It's not released yet. For the time being you can use `oauthRequest()`

**Comment by SpyTec** [comment]
@krrishdholakia it should be released in v1.19.0

**Comment by exzizt** [comment]
Thank you guys for implementing this. I really appreciate it!
