### ISSUE TITLE
Comment sifting question

### ISSUE THREAD

**Issue by cdoern** [not-an-aardvark/snoowrap#165]
Is there a way to sift through comments after they have been posted on specific post and run a check for all of them? I know you can see if as comment contains a specific response using snoostorm right when it is posted, but is there a way to get all comments and run them through a for each loop testing for a condition?

**Comment by not-an-aardvark** [comment]
Yes, try using [`expandReplies`](https://not-an-aardvark.github.io/snoowrap/VoteableContent.html#expandReplies__anchor).
