### ISSUE TITLE
view_count of some submissions is null no matter what 

### ISSUE THREAD

**Issue by 1065212030** [not-an-aardvark/snoowrap#168]
On a submission, the view_count propertie is null sometimes. Checking the reddit API itself confirms that view_count actually have values there, but is still null when checked with Snoowrap.
`
const Reddit = require('snoowrap');  

let client = new Reddit({  
        userAgent: 'me',  
        clientId: clientId,  
        clientSecret: clientSecret,  
        username: username,  
        password: password,  
});  
let data = await client.getMe().getSubmissions().fetchAll();  
let res = data.reduce((pre, item) => {  
       pre.view_count += item.view_count;  
}, {view_count: 0});  
`
it's so baffling to me that some view_count property is null.

Am I doing something wrong?

**Comment by not-an-aardvark** [comment]
I think the view count of a post can only be seen by moderators of the subreddit where the post appears.

**Comment by 1065212030** [comment]
thanks for your anwsering,but there are only some view count of a post are invisible so that i can not get accurate data.

**Comment by SpyTec** [comment]
Hi @1065212030,

`view_count` does not exist for older entries as view count on submissions was added sometime last year if I remember correctly. You should be able to see it if you're using `getMe()` or if you are a moderator of the subreddit you are checking the submissions from. But only given the submissions were created after the announcement of view count being added

**Comment by 1065212030** [comment]
@SpyTec
i'm sure the submissions are created recently, and submission's view_count is null sometimes. For instance, today i can get the value, but tomorrow i get null.

**Comment by SpyTec** [comment]
@1065212030 You could check if there is an issue with fetching the data. Seeing as you access it whether or not an error occurred. I added a catch to the following:
```js
const Reddit = require('snoowrap');

let client = new Reddit({
    userAgent: 'me',
    clientId: clientId,
    clientSecret: clientSecret,
    username: username,
    password: password,
});
let data = await client.getMe().getSubmissions().fetchAll().catch(err => new Error(err));
if (data instanceof Error) {
    console.log(data)
    return;
}
let res = data.reduce((pre, item) => {
pre.view_count += item.view_count;
}, {view_count: 0});
```

**Comment by 1065212030** [comment]
@SpyTec i do what you recommend these days, but it didn't work. it didn't capture err message and i get null again.

**Comment by SpyTec** [comment]
Sorry for the late answer. @1065212030, it seems Reddit has disabled view count for everyone. Hence why it is returning null

See https://www.reddit.com/r/changelog/comments/a74eor/we_disabled_the_view_count_feature/
