### ISSUE TITLE
expandReplies usage issue

### ISSUE THREAD

**Issue by cdoern** [not-an-aardvark/snoowrap#169]
`  r.getSubmission(dailyp).expandReplies().then(function (comments){
        comments.forEach(function (post){`
(dailyp is a var with a post id stores inside)
when using expand replies throws an error saying "comments.forEach is not a function" I just want to traverse through all comments in a post at once accessing body, user etc how can I do this!

**Comment by SpyTec** [comment]
Going from the source code now and haven't tested it. But try

```js
r.getSubmission(dailyp).fetch().then(function (submission) { 
    submission.comments.forEach(function (comment){
```

`fetch()` will get us the submission itself and allow us to access comments.

**Comment by Amndeep7** [comment]
Expand replies returns the submission thread object.  Your function calls should probably look like this: `r.getSubmission(asdf).expandReplies().then(thread => { thread.comments.forEach((comment) => whatever); });`
