### ISSUE TITLE
Snoowrap getMe() doesn't return expected values

### ISSUE THREAD

**Issue by scroobius-pip** [not-an-aardvark/snoowrap#171]
I've obtained a reddit access token with scopes 'identity' and 'account'
I pass the access token and user agent string to the snoowrap constructor:

`

    const r = new snoowrap({
        accessToken,
        userAgent: 'node:projeckebab:v0.0.1 (by /u/sim04ful)',
    })

    const me = await r.getMe()
    console.log(me)`

but getMe() doesn't return any of the expected values instead it returns this: 

`RedditUser { features:
   { do_not_track: true,
     chat_subreddit: true,
     show_amp_link: true,
     mweb_xpromo_revamp_v2: { owner: 'growth', variant: 'control_2', experiment_id: 457 },
     top_content_email_digest_v2: { owner: 'growth', variant: 'control_2', experiment_id: 363 },
     mweb_xpromo_interstitial_comments_ios: true,
     mweb_xpromo_modal_listing_click_daily_dismissible_ios: true,
     chat_group_rollout: true,
     mweb_sharing_clipboard: { owner: 'growth', variant: 'control_1', experiment_id: 315 },
     spez_modal: true,
     mweb_xpromo_modal_listing_click_daily_dismissible_android: true,
     swap_steps_two_and_three_recalibration: { owner: 'growth', variant: 'treatment_4', experiment_id: 324 },
     mweb_xpromo_interstitial_comments_android: true }}
`

But according to the documentation it's meant to return something of the form:

`RedditUser { is_employee: false, has_mail: false, name: 'snoowrap_testing', ... }`

**Comment by SpyTec** [comment]
So the `accessToken` you sent in was an object and not a string? Should be an easy fix
