### ISSUE TITLE
Geo filter of hot list does't work

### ISSUE THREAD

**Issue by BG-Kim** [not-an-aardvark/snoowrap#182]
I want to get a list of popular topics for each country.
eg) https://www.reddit.com/r/popular/?geo_filter=CA

So, I search reddit api 
https://www.reddit.com/dev/api/
and reference to GET [/r/subreddit]/hot

I request blow
r.getHot('popular', {g:'CA'}).map( post=> {return {"title" : post.title, "score" : post.score, "url" : post.url}} ).then( (result)=> {
	console.log(result);	
});

But, g option is doesn't work. I received all same result.

I put on other option. eg limit, it works.
I think it seem to reddit api bug. But, I cannot found API bug report in reddit.

extra info)
I check request_handle.js for found reason. request is :
https://oauth.reddit.com/r/popular/hot?raw_json=1&count=9999&g=CA

**Comment by SpyTec** [comment]
I'm not able to replicate it. Seems to either be a bug, not implemented, or part of an A/B test which we're not part of

**Comment by SpyTec** [comment]
I wonder, does it work if you change `g` to `geo_filter`?

**Comment by BG-Kim** [comment]
> I wonder, does it work if you change `g` to `geo_filter`?

No, It's don't work.

**Comment by SpyTec** [comment]
I'm going to go on a limb and say it's broken. You might be able to create a post on r/redditdev about it

**Comment by SpyTec** [comment]
Closing this. If anyone can get this to work or know it works on other wrappers you can reopen it. 

For now I will say this is not a snoowrap issue
