### ISSUE TITLE
XMLHttpRequest has been blocked by CORS policy for getSubmission().reply()

### ISSUE THREAD

**Issue by MokoPolo** [not-an-aardvark/snoowrap#183]
I basically do
    const r = new snoowrap({
      userAgent: "My bot",
      clientId: process.env.REACT_APP_CLIENT_ID,
      clientSecret: process.env.REACT_APP_AUTHORIZATION,
      refreshToken: process.env.REACT_APP_REFRESH_TOKEN
    });
r.getSubmission("t3_3ytre4").reply("test"); and I get:

Access to XMLHttpRequest at 'https://www.reddit.com/api/v1/access_token' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I am running this code from a browser. Could that be the issue?

**Comment by SpyTec** [comment]
It shouldn't be an issue, I'm currently running snoowrap in the browser without any problems.

I can run some tests later today. But are you sure refresh token and everything is correct? If you add `r.config({debug: true})`, what does it output throughout the code?

**Comment by MokoPolo** [comment]
Refresh token should be good. I also can do further testing today. But I changed code to:

    const r = new snoowrap({
      userAgent: "My bot",
      clientId: process.env.REACT_APP_CLIENT_ID,
      clientSecret: process.env.REACT_APP_AUTHORIZATION,
      refreshToken: process.env.REACT_APP_REFRESH_TOKEN
    });
    r.config({ debug: true });

On console messages:

POST https://www.reddit.com/api/v1/access_token 401
Access to XMLHttpRequest at 'https://www.reddit.com/api/v1/access_token' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
![Error](https://user-images.githubusercontent.com/3758891/55234030-8c5ea000-5200-11e9-8f31-d6e24f98938a.PNG)

**Comment by MokoPolo** [comment]
Hello,

I took a look at your code and it gave me idea. I double checked the parameters I was using and it turned out my secret was wrong and it works now. Thank you for your help!
