### ISSUE TITLE
Unhandled rejection

### ISSUE THREAD

**Issue by marataziat** [not-an-aardvark/snoowrap#184]
```
r.getHot().map(post => post.title).then(console.log);
Unhandled rejection l@https://not-an-aardvark.github.io/snoowrap/snoowrap-v1.min.js:1:49
[23]</e.exports/</n.onload/f<@https://not-an-aardvark.github.io/snoowrap/snoowrap-v1.min.js:3:7807
[23]</e.exports/</n.onload@https://not-an-aardvark.github.io/snoowrap/snoowrap-v1.min.js:3:7966
snoowrap-v1.min.js:3:31626
```
How to fix this? requests to https://www.reddit.com/api/v1/access_token says bad request! 
```
<script src="https://not-an-aardvark.github.io/snoowrap/snoowrap-v1.min.js"></script>
<script>
const r = new snoowrap({
  clientId: 'Tf27LRQ7VTQFXw',
  clientSecret: 'REDACTED',
  refreshToken: 'put your refresh token here'
});
</script>
```
I have set everything right!

**Comment by SpyTec** [comment]
Hi, 

First of: you shouldn't reveal your secret publicly as you did just now. I urge you to go to the [prefs/apps](https://www.reddit.com/prefs/apps/) and regenerate a new one to make the current one invalid. Then keep it private.

Secondly, you need a refreshToken in this case, which you can get by either following OAuth protocol or by utilizing https://not-an-aardvark.github.io/reddit-oauth-helper/

**Comment by marataziat** [comment]
Every user has unique refreshToken?

**Comment by marataziat** [comment]
Can I generate refresh tokens on browser side?

**Comment by marataziat** [comment]
When I remove my secret key like this:
```
const r = new snoowrap({
  clientId: 'Tf27LRQ7VTQFXw',
  refreshToken: '284121441002-IIJHpmblNDSvOBmUd60I1ErdN2U'
});
```

I says 
```
Error: Missing credentials passed to snoowrap constructor. You must pass an object containing either (a) userAgent, clientId, clientSecret, and refreshToken properties, (b) userAgent and accessToken properties, or (c) userAgent, clientId, clientSecret, username, and password properties. For information, please read the docs at https://not-an-aardvark.github.io/snoowrap/.
```
When I add clientSecret:
```
  clientSecret: 'SomeSecret',
```
It works!

**Comment by not-an-aardvark** [comment]
I've edited your comment to remove the `clientSecret` and `refreshToken` -- you shouldn't post either of these publicly, because someone could use them to access your reddit account.

If your reddit app is has the "Installed App" type when you view it on https://reddit.com/prefs/apps, then you should include an empty string as the `clientSecret`.

Yes, you should have a different `refreshToken` for each user. A `refreshToken` allows access to a specific user's reddit account.

**Comment by marataziat** [comment]
Don't worry, it's my test account. Thank you for your quick reply :)

**Comment by marataziat** [comment]
But how to use it if it does not work without secret? I will inject it into HTML to users be able to use my app :)?

**Comment by not-an-aardvark** [comment]
An "installed app" does not have a secret.

If you want users to access your app through their own reddit account, you should use something like [`getAuthUrl`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#.getAuthUrl__anchor) and [`fromAuthCode`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#.fromAuthCode__anchor) to create a snoowrap instance. You can provide an empty string (`""`) as the `clientSecret` property.

**Comment by marataziat** [comment]
When I try to use snoowrap with angular:
```
import "snoowrap"
```
it says ```Module not found: Error: Can't resolve 'stream' in 'C:\Users\Marat\Desktop\RedditGrid\node_modules\snoowrap\dist\objects'``` :(

**Comment by marataziat** [comment]
https://stackoverflow.com/a/51778962 solved
