### ISSUE TITLE
Why it says Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oauth.reddit.com/hot?raw_json=1&count=9999&t=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]?

### ISSUE THREAD

**Issue by marataziat** [not-an-aardvark/snoowrap#185]
Yes, if you give wrong oauth data you can't get token:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.reddit.com/api/v1/access_token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]
```
I'm doing:
```
var rrr = new snoowrap({
  clientId: 'Tf27LRQ7VTQFXw', // My app ID
  clientSecret: 'HodDcI8THktZKwHf5Q2_mq32WXX', // Invalid token some letters I have changed I get it from oauth redirect in &code= 
  refreshToken: "" // Leave, it's not installed app 
});

rrr.getHot()
```
And I get:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oauth.reddit.com/hot?raw_json=1&count=9999&t=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
Why dudes :(? CORS failed not on access_token getting level, on hot?raw_json=1&count=9999&t= level why? Reddit disabled their CORS api?

**Comment by SpyTec** [comment]
You shouldn't reveal your secret publicly as you did just now. I urge you to go to the prefs/apps and regenerate a new one to make the current one invalid. Then keep it private to yourself.

Refresh token is always needed. Unless you get the client to retrieve it you have to generate it yourself before you can use the application. You can use https://not-an-aardvark.github.io/reddit-oauth-helper/ to get one

See https://not-an-aardvark.github.io/snoowrap/snoowrap.html#snoowrap

**Comment by marataziat** [comment]
How will i generate it on production? I have to run server to get refresh tokens?

**Comment by SpyTec** [comment]
Only way to not use clientId/clientSecret is to use username/password instead. Though you will not get access to all the Reddit endpoints and the ratelimit will be reduced.

OAuth2 requires refreshToken for persistent applications. If you don't have a server but run this in the browser or something you can still get around this by using implicit flow and letting the front-end handle authentication.

I don't know what you're doing, so I can't really give any tips apart from that.

**Comment by SpyTec** [comment]
If this is a bot of some kind, generate it manually once then give it to the bot.

**Comment by marataziat** [comment]
No, I want to auth my users in browser!

**Comment by marataziat** [comment]
How to use implicit flow?

**Comment by SpyTec** [comment]
Create an installed app on Reddit, set `clientSecret` as empty string, then use clientId with refreshToken. The users themselves retrieve the `refreshToken` by using OAuth flow:

1. Give them oauth url
2. User goes to url and authenticates with Reddit
3. Use code to authenticate.

There's more to it, but that's the very very basic workflow. I'd recommend to see documentation or some YouTube videos that goes over it more.

**Comment by marataziat** [comment]
Yay, now it works but ``` r.getSubmission('2np694').author.name``` says ```Proxy { <target>: targetFunc(), <handler>: {…} }```

**Comment by marataziat** [comment]
Oh I need to use .then :)
