### ISSUE TITLE
Known vulnerability in `ws` < 3.3.0

### ISSUE THREAD

**Issue by anulman** [not-an-aardvark/snoowrap#187]
Just received a notification about a vulnerability in one of my projects, related to a transitive dependency on `ws` via `snoowrap`. Suggest upgrading ASAP.

![image](https://user-images.githubusercontent.com/721128/58928376-46521b00-8720-11e9-8eef-4c16623eac1b.png)

**Comment by anulman** [comment]
@not-an-aardvark Hate to pester again, but would you mind cutting a new release, e.g. 1.16.1? Just got another notification note; seems this PR didn't make last week's update.

**Comment by not-an-aardvark** [comment]
Published in v1.17.0.
