### ISSUE TITLE
TypeScript migration discussion

### ISSUE THREAD

**Issue by SpyTec** [not-an-aardvark/snoowrap#192]
Should we consider migrating to TypeScript? It would give us better and stronger types, give us static analysis, and make Snoowrap work better for TypeScript projects. 

It would also allow us to create interfaces for API responses so it is better documented what responses we get, snoowrap wouldn't break if more properties are added to the responses.

There's three things we could do if we do not have anything against it.

1. Migrate existing code to TypeScript incrementally,
2. Create TS definitions for existing classes, or
3. Combination of 1 and 2.

If we agree on migrating to TypeScript we do not need to do it all in one go. We can migrate one file at a time and do so in our own pace. Tests do not need to change. We would still be able to use ESLint given `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` is added

If we agree only on TS definitions, this would be a `.d.ts` file next to every file we currently have which would remove the need for DefinitelyTyped's snoowrap definitions. No changes would need to be made with existing code.

I can create a tracking issue if we agree on any options

**Comment by not-an-aardvark** [comment]
I'm open to the idea of this -- I have no strong preferences on the implementation. I remember I tried migrating to TypeScript very early in the project's development and gave up because the "promise chaining" behavior seemed difficult to express in the type system, but I haven't looked at the problem very deeply.

**Comment by SpyTec** [comment]
I haven't seen anything odd over on the [@types/snoowrap](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/snoowrap) which provides all the definitions for the project right now. Would we migrate to TypeScript it would behave the same way, if they do anything odd there that I haven't spotted we would probably need to implement it that way as well.

I'll create a tracking issue about what needs to be done in the next week or two if no one has anything else to offer

**Comment by markspolakovs** [comment]
I think the best approach is to do Step 2, then Step 1. Once we have definitions for all the classes, we can  add the typedefs directly in the `snoowrap` package and mark the DefinitelyTyped defs as a stub, so if and when we do a full TypeScript migration consumers don't have to change anything.

An option could be to copy in the current DT definitions, but we'd have to get the permissions of the contributors, as the Snoowrap definitions don't have a clear LICENSE ("Copyrights are respective of each contributor listed at the beginning of each definition file.").

**Comment by SpyTec** [comment]
Sounds good. Couldn't see any headings in other files than index.d.ts though. @vitosamson @TheAppleFreak @willwull, do you grant us permission to copy over the snoowrap definitions?

**Comment by willwull** [comment]
No complaints from me 👍

**Comment by TheAppleFreak** [comment]
None from me either 👍

**Comment by vitosamson** [comment]
^ same

**Comment by SpyTec** [comment]
Thanks all! Feel free to unsubscribe on the right of the issue if you don't want updates :)

It seems like if we want to support TS modules we'd need Babel 7, I took the liberty on working on this now rather than later - as well as worked on trying to move d.ts to `/dist`, though not successful yet. 

Tracking the PR on #200 - suggestions or PRs to the branch is most welcome!
