### ISSUE TITLE
How to see if a comment is replying to a certain user and contains a certain string?

### ISSUE THREAD

**Issue by TTT2866** [not-an-aardvark/snoowrap#197]
Is there a way to see if the comment is replying to a specific user (my bot) and contains a specific string?

for example, while streaming replies 
 if (comment.replyingTo === '/u/username123thisIsMyBot') ...
and then 
 if (comment.body === '1+1') {
comment.reply("1+1 = 2");

Cheers

**Comment by SpyTec** [comment]
You could check comment replies with `snoowrap.getUnreadMessages` AFAIK. As long as comment reply PMs are enabled

**Comment by TTT2866** [comment]
Awesome thank you, I think this is what I'm looking for. do you know if theres a way to get only the 'body' of the replies? 
Assumed its something like 

 r.getUnreadMessages().then(console.log(listing.body)) 

but it just throws errors

**Comment by SpyTec** [comment]
You just get an array (through a Listing class) with PrivateMessages and Comments in it.

Try doing just `r.getUnreadMessages().then(console.log)` to see what is outputted

**Comment by TTT2866** [comment]
That then outputs the following

Listing [ Comment { first_message: null,
  first_message_name: null,
  subreddit: Subreddit { display_name: 'BleachBraveSouls' },
  likes: null,
  replies: Listing [],
  id: 'eufoz3n',
  subject: 'comment reply',
  was_comment: true,
  score: 1,
  author: RedditUser { name: 'TTT334' },
  num_comments: 41,
  parent_id: 't1_eufn969',
  subreddit_name_prefixed: 'r/BleachBraveSouls',
  new: true,
  body: ':)',
  link_title: 'Choose a 6* available characters',
  dest: 'username1234',
  body_html:
   '<div class="md"><p>:)</p>\n</div>',
  name: 't1_eufoz3n',
  created: 1563813060,
  created_utc: 1563784260,
  context:
   '/r/BleachBraveSouls/comments/cga0e9/choose_a_6_available_characters/eufoz3n/?context=3',
  distinguished: null } ]

**Comment by SpyTec** [comment]
Yes, you get an array which contains one element right now, a comment. You can get the body of it and check the RegEx on that

**Comment by TTT2866** [comment]
Yeah haha I'm just having trouble working out _how_ to get the body from it though

Still super new to Node JS but i'm trying to use things like this with no avail

if (r.getUnreadMessages.includes(":(")) ===  true {
	console.log("true");
}

**Comment by SpyTec** [comment]
NodeJS and JS is more or less the same thing, NodeJS has some functionality to work with the system though. I'd recommend looking at some JS tutorials or walkthroughs of some simple applications

You would need to do something like
```js
r.getUnreadMessages().forEach(item => {
  if (item instanceof Comment && item.body.includes(":(") {
    console.log(true);
  }
});
```

**Comment by TTT2866** [comment]
Yeah I still can't get it to work :( 
Thanks heaps for the help though, I'll have to read up on it a bit more when I have the time

  if (item instanceof Comment && item.body.includes(":(") {
SyntaxError: Unexpected token {

**Comment by SpyTec** [comment]
Oops, forgot a closing parentheses

```js
r.getUnreadMessages().forEach(item => {
  if (item instanceof Comment && item.body.includes(":(")) {
    console.log(true);
  }
});
```

**Comment by TTT2866** [comment]
Haha now it's just saying the comment isn't defined. Tried to change it to a lowercase 'c' and still the same problem

Unhandled rejection ReferenceError: comment is not defined

**Comment by SpyTec** [comment]
You need to import it from snoowrap. If you're importing the whole of snoowrap you can try `snoowrap.Comment`

**Comment by TTT2866** [comment]
Hm it's giving me the following error still after using this 
r.getUnreadMessages().forEach(item => {
  if (item instanceof snoowrap.Comment && item.body.includes(":(")) {
    console.log(true);
  }
});

I've got this at the top of the script and tried putting it just above the r.getUnreadMessage part too 
const Snoowrap = require('snoowrap');


Unhandled rejection ReferenceError: snoowrap is not defined
    at r.getUnreadMessages.forEach.item (C:\Users\HUM0014\Desktop\Redditbot\reddit.js:68:23)

**Comment by SpyTec** [comment]
I'd recommend looking up some guides or walk-throughs on JavaScript
