### ISSUE TITLE
Add TS definitions to ModmailConversation

### ISSUE THREAD

**Issue by SpyTec** [not-an-aardvark/snoowrap#201]
No .d.ts files exists for ModmailConversation or ModmailConversationAuthor. This should be added.

Note: New modmail responses can be tricky to decode as it seems to move fields around and re-use them for different purposes

**Comment by markspolakovs** [comment]
I have a draft on my laptop that I was working on for DefTyped, I'll submit it later today at the airport

**Comment by SpyTec** [comment]
Sounds good
