### ISSUE TITLE
Missing () In The Documentation Code

### ISSUE THREAD

**Issue by SaishNarvekar** [not-an-aardvark/snoowrap#205]
In documentation sample code for [`getRandomSubmission()`](https://not-an-aardvark.github.io/snoowrap/Subreddit.html) 
Expected :
`r.getSubreddit('snoowrap').getRandomSubmission().then(console.log)`
Actual : 
`r.getSubreddit('snoowrap').getRandomSubmission.then(console.log)`

![Github Issue](https://user-images.githubusercontent.com/35778345/62825905-d43efc00-bbd0-11e9-979e-478d7586b91f.JPG)

**Comment by SpyTec** [comment]
Thanks! It's been fixed
