### ISSUE TITLE
issue with CORS on oauth flow on browser

### ISSUE THREAD

**Issue by obiwankenoobi** [not-an-aardvark/snoowrap#210]
I cant make the oauth flow to work on the browser, the issue is very similar to [this](https://github.com/not-an-aardvark/snoowrap/issues/185)

I tried to follow [those](https://github.com/not-an-aardvark/snoowrap/issues/185#issuecomment-488844987) instructions but I think I am doing something wrong as I am still getting this CORS issue
 
my flow is as follow:

1. creating oauth url:

```js 
function createAuth1() {
  console.log("creating auth")
    const authenticationUrl = snoowrap.getAuthUrl({
      clientId: 'client_id_from_reddit(installed app)',
      scope: ['identity', 'wikiread', 'wikiedit'],
      redirectUri: 'http://10.0.0.4:3000/',
      permanent: false,
      state: 'fe211bebc52eb3da9bef8db6e63104d3' // a random string, this could be validated when the user is redirected back
    });
    window.location = authenticationUrl
}

```

2. after redirection extracting the `code`

```js
const code = new URL(window.location.href).searchParams.get('code')
```

3. creating instance where `token` is the extracted `code`

```js
function createInstance(token) {
  return new snoowrap({
    userAgent:"Bot",
    clientId:"client_id_from_reeddit(installed app)",
    clientSecret:"",
    refreshToken:token,
  })
}
```

4. trying to use it

```js
const instance = createInstance(code)
console.log(await instance.getHot())
```

**Comment by SpyTec** [comment]
If you are using it in browser, do not use `clientSecret`. Instead, create an installed app on Reddit so it will use implicit flow. Then just provide clientSecret as empty string. Hopefully that should work :)

**Comment by SpyTec** [comment]
Right, forgot myself for a second. So you should use `snoowrap.fromAuthCode` when you first authenticate. From then on you can use `new snoowrap` whenever you refresh

https://not-an-aardvark.github.io/snoowrap/snoowrap.html#.fromAuthCode__anchor

**Comment by obiwankenoobi** [comment]
Thanks for super quick reply! So when I am using `snoowrap.fromAuthCode` for first authentication, it works great. Then I am trying to refresh the page and use instead:  

```js
function createInstance(token) {
  return new snoowrap({
    userAgent:"Bot",
    clientId:"client_id_from_reeddit(installed app)",
    clientSecret:"",
    refreshToken:token,
  })
}
```

and I am getting :

```
{
  "statusCode": 400,
  "body": {
    "message": "Bad Request",
    "error": 400
  },
  "headers": {
    "content-length": "40",
    "x-moose": "majestic",
    "content-type": "application/json; charset=UTF-8",
    "cache-control": "max-age=0, must-revalidate"
  },
  "request": {
    "method": "POST",
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "www.reddit.com",
      "port": null,
      "hostname": "www.reddit.com",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/api/v1/access_token",
      "path": "/api/v1/access_token",
      "href": "https://www.reddit.com/api/v1/access_token"
    }
  }
}
```

**Comment by SpyTec** [comment]
After using `fromAuthCode` you need to get the `refreshToken` from it. You can use that together with clientId to get a new `accessToken`

**Comment by obiwankenoobi** [comment]
My `refreshToken` prop was `null` on the instance created from `fromAuthCode`. But I noticed that I had prop `accessToken` there. So I tryed to use it with `new snoowrap` and it worked great! My 

```js
function createInstance(accessToken) {
  return new snoowrap({
    userAgent:"Bot",
    clientId:"client_id_from_reeddit(installed app)",
    clientSecret:"",
    accessToken: accessToken,
  })
}
```  

Hmm.. I hope its the right way to do it! Thanks for the help! (:

**Comment by SpyTec** [comment]
IIRC `refreshToken` is not given if you authenticate for 1h instead of forever. `refreshToken` is the token that can retrieve a new `accessToken` one it has expired, which is quite useful so you don't have to re-authenticate so often

**Comment by obiwankenoobi** [comment]
Yes I changed `permanent: false` to `permanent: true` and I can see it now. Well It's all looks good. Hope this is it! Thank you very much! (:

**Comment by Lermatroid** [comment]
Sorry to re open this thread. But can you tell me what you meant by set permeant from false to true?

**Comment by SpyTec** [comment]
> 
> 
> Sorry to re open this thread. But can you tell me what you meant by set permanent from false to true?

@Lermatroid Permanent being false means you only have access to the account for 1h. Permanent keeps the access forever as long as you have the tokens.

```js
const authenticationUrl = snoowrap.getAuthUrl({
  clientId: 'client_id_from_reddit(installed app)',
  scope: ['identity', 'wikiread', 'wikiedit'],
  redirectUri: 'http://10.0.0.4:3000/',
  permanent: false, // @Lermatroid this one
  state: 'fe211bebc52eb3da9bef8db6e63104d3' // a random string, this could be validated when the user is redirected back
});
```

**Comment by charludo** [comment]
Sorry to reopen this again.... But I'm having the exact issue `obiwankenoobi` had two years ago. I'm able to follow the proposed changes and solutions 1:1:

1.  creating OAuth URL:
    ```js
    var authenticationUrl = snoowrap.getAuthUrl({
        clientId: '<my client id>',
        scope: ["identity", "read"],
        redirectUri: 'http://localhost:3000/authed',
        permanent: true
    });
    window.location.href = authenticationUrl;
    ```

2. at the /authed endpoint, create a new snoowrap instance from the code reddit returns:
    ```js
    function createInstance(token) {
	    return new snoowrap({
		    userAgent: '<my user agent string>',
		    clientId: '<my cliend id>',
		    clientSecret: '', // empty!
		    refreshToken: token
	    })
    }
    ```

3. use that instance:
    ```js
    async function use_it() {
        var code = new URL(window.location.href).searchParams.get('code');
        const instance = await createInstance(code);

        try {
              console.log(await instance.getHot())
        } catch(e) {
              console.log(JSON.stringify(e, null, 2))
        }
    }
    ```

The result is (predictably) the same as it was for obiwankenoobi:
```
{
  "statusCode": 400,
  "body": {
    "message": "Bad Request",
    "error": 400
  },
  "headers": {
    "content-length": "40",
    "x-moose": "majestic",
    "content-type": "application/json; charset=UTF-8",
    "cache-control": "max-age=0, must-revalidate"
  },
  "request": {
    "method": "POST",
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "www.reddit.com",
      "port": null,
      "hostname": "www.reddit.com",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/api/v1/access_token",
      "path": "/api/v1/access_token",
      "href": "https://www.reddit.com/api/v1/access_token"
    }
  }
}
```


Changing `refreshToken` to `accessToken` (like obiwankenoobi mentioned), the response changes to 
```
{
  "isTrusted": true
}
```

\- which seems good, but also now comes with a CORS error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oauth.reddit.com/hot?raw_json=1&count=9999&t=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

It seems the original solution was to set `permanent: true` in `getAuthUrl()` and then use `refreshToken`, but that doesn't change the result for me (see above).

What am I missing here? I've been trying around for hours, and still no look. Any help would be appreciated.

**Comment by charludo** [comment]
Nevermind - figured it out. For anyone else with the same problem:

The auth-code used in `fromAuthCode` can only be used **once**. 

Do Step 1 as above, then change step 2 to:

```js
Snoowrap.fromAuthCode({
    code: code,
    userAgent: '<your user agent>,
    clientId: '<your client id>,
    clientSecret: '', //empty
    redirectUri: '<your redirect uri, same as in reddit application config>'
}).then(r => {
    const token = r.refreshToken; //this!! this is the refresh token!! not the code returned from reddit!!
    // do something with the token. I put it in localstorage.
    localStorage.setItem("refreshToken");
});
```

And *now* you can create a request object.
```js
async function foo() {
    var token = await localStorage.getItem("refreshToken");
    const request = new Snoowrap({
        userAgent: '<your user agent>',
        clientId: '<your client id>',
        clientSecret: '', //empty
        refreshToken: token
    });
    return await session;
}
```
