### ISSUE TITLE
error TS2420: Class 'RedditContent<T>' incorrectly implements interface 'Promise<T>'.

### ISSUE THREAD

**Issue by cnettelblad** [not-an-aardvark/snoowrap#216]
Trying to compile the following:

main.js
```typescript
import snoowrap from 'snoowrap'

const reddit = new snoowrap({
  // Hiding this
})
```

tsconfig
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*"]
    }
  },
  "include": [
    "src/**/*"
  ]
}
```

And I receive the following error:

```bash
error TS2420: Class 'RedditContent<T>' incorrectly implements interface 'Promise<T>'.
  Property 'then' is missing in type 'RedditContent<T>'.

3 export default class RedditContent<T> implements Promise<T> {

```

**Comment by SpyTec** [comment]
I've tried that exact same tsconfig as well as the code. Not getting any TS errors.
Since that code isn't implementing Promise but rather extending it I don't see how that error could occur - it's not changed since 2018

**Comment by cnettelblad** [comment]
That's interesting. I'll continue investigating and get back.

**Comment by cnettelblad** [comment]
This is so embarrassing, I'll close this issue and apologize for wasting your time.

(The issue was entirely on my end, I had accidentally parsed it in a very reckless S&R, shame on me..)
