### ISSUE TITLE
Why do dates requested by api not pull the correct date on reddit

### ISSUE THREAD

**Issue by Plexversal** [not-an-aardvark/snoowrap#217]
`r.getSubmission(`9067f2`).fetch().then(s => {
  console.log(s.created_utc)
})`

This will output with:
> 1532009773

Which when put into a date constructor outputs with **1970-01-18T17:33:29.773Z** which is obviously not the date created on reddit. This will happen with all submissions and provides dates close to that during 1970 and presumably comments too, everything else requested regarding specific posts like title, id, etc.. pulls fine, except the dates (created and created_utc) giving outputs like that.

How would I get its exact date provided on reddit?

**Comment by SpyTec** [comment]
Date takes ms, returned output from Reddit is in seconds. Simply multiply by 1000
```js
>new Date(1532009773*1000)
Date Thu Jul 19 2018 16:16:13 GMT+0200 (Central European Summer Time)
```
