### ISSUE TITLE
snoowrap constructor for reddit installed app.

### ISSUE THREAD

**Issue by callumPearce** [not-an-aardvark/snoowrap#220]
Hi, I was wondering if there is any possibility of getting snoowrap to connect to reddit using an installed app, whereby only a `userAgent` and `clientID `are supplied to the `snoowrap` constructor. Similar to how that implemented in the `praw` package here:

https://praw.readthedocs.io/en/latest/code_overview/reddit_instance.html

Thanks,
Cal

**Comment by SpyTec** [comment]
Hi!

Installed app does exist but we haven't released it yet. I'll let you know when it's released

**Comment by callumPearce** [comment]
Thank you, I look forward to it. If you need any extra help on features I would be happy to contribute.

**Comment by callumPearce** [comment]
Great, thanks.
