### ISSUE TITLE
Compilation of projects that use snoowrap fails with TypeScript Version 3.7.0-beta

### ISSUE THREAD

**Issue by paul-soporan** [not-an-aardvark/snoowrap#224]
### Issue:
Compilation of projects that use snoowrap fails with TypeScript Version 3.7.0-beta.

I don't know what changes in TS have broken snoowrap, but I think that the issue can be solved by changing `Subreddit` to `_Subreddit` and `RedditContent` to `_RedditContent`

***
### Technical Details:
* **Tested on Linux Distributions**
* **node**: v12.9.1
* **npm / npx**: 6.11.3
* **TypeScript / tsc**: Version 3.7.0-beta
* **snoowrap**: 1.19.0
***
### Terminal Logs:
```
$ npx tsc

node_modules/snoowrap/dist/snoowrap.d.ts:163:38 - error TS2304: Cannot find name 'RedditContent'.

163   export interface ModAction extends RedditContent<ModAction> {
                                         ~~~~~~~~~~~~~

node_modules/snoowrap/dist/snoowrap.d.ts:167:16 - error TS2304: Cannot find name 'Subreddit'.

167     subreddit: Subreddit;
                   ~~~~~~~~~

node_modules/snoowrap/dist/snoowrap.d.ts:196:9 - error TS2304: Cannot find name 'RedditUser'.

196     to: RedditUser | Subreddit | string;
            ~~~~~~~~~~

node_modules/snoowrap/dist/snoowrap.d.ts:196:22 - error TS2304: Cannot find name 'Subreddit'.

196     to: RedditUser | Subreddit | string;
                         ~~~~~~~~~

node_modules/snoowrap/dist/snoowrap.d.ts:199:21 - error TS2304: Cannot find name 'Subreddit'.

199     fromSubreddit?: Subreddit | string;
                        ~~~~~~~~~

node_modules/snoowrap/dist/snoowrap.d.ts:212:17 - error TS2304: Cannot find name 'Subreddit'.

212     subreddit?: Subreddit | string;
                    ~~~~~~~~~


Found 6 errors.
```
***
### Steps to Reproduce:
1) Create a new TypeScript Project
2) import snoowrap
3) Compile it with `tsc` Version 3.7.0-beta
***

**Comment by SpyTec** [comment]
Thanks for reporting this. I noticed you created a commit for it on your end, can you open a PR?

**Comment by paul-soporan** [comment]
Sure!
Rebased the changes and opened a PR: #226
