### ISSUE TITLE
How to get parent comment of the bot invocation comment?

### ISSUE THREAD

**Issue by zaygozi** [not-an-aardvark/snoowrap#229]
The scenario is that A posts a comment. B replies to that comment by invoking the bot. Typically snoowrap provides info about B and the original post. How do I get a comment object for A?

REFER : [Stackoverflow Question](https://stackoverflow.com/q/58364343/8619824)

**Comment by SpyTec** [comment]
There's a `parent_id` field you can utilize. This will give you the full id e.g `t1_f37dwqc` which you can then fetch the data from.

the `t{x}_` prefix is what type it is. `t1_` is a comment so you can call `r.getComment(id)`, or `r.getSubmission(id)` if the prefix is `t3_`

**Comment by zaygozi** [comment]
@SpyTec Thanks for the prompt response. Although I read the docs, I never saw a section explaining the various parameters returned by the comments object. Maybe I just missed it. Thanks once again.

**Comment by SpyTec** [comment]
@zaygozi one advice I have is that you can always print out the object to see what is there. It should give you some insight into what you can do.

Reddit also has the ability to add .json to domains, e.g. https://old.reddit.com/r/EliteDangerous/.json
