### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by heondo** [not-an-aardvark/snoowrap#230]
![image](https://user-images.githubusercontent.com/47020765/66720508-5bb41180-edb2-11e9-80bc-1c7bc5fc156f.png)

After googling this issue everyone seems to be able to fix it by **making their api project a personal use script** and not a web app which **I've already done**. I have the right client id and client secret values along with the refresh token made through the oauth helper but I still get this error message for any request. I have unsuccesfully made a single request so far

```
const snoowrap = require('snoowrap');
const r = new snoowrap(redditCreds);
console.log(r);

r.getHot().map(post => post.title).then(console.log).catch(err => console.error(err));```

**Comment by SpyTec** [comment]
Just to double-check. You created a *permanent* refresh token which you then added to the credentials, correct?

**Comment by heondo** [comment]
@SpyTec yes from the same link I've set the redirect uri to `https://not-an-aardvark.github.io/reddit-oauth-helper/`
![image](https://user-images.githubusercontent.com/47020765/66721642-a2593a00-edb9-11e9-98c7-582225bf8a7f.png)

**Comment by ZHamburglar** [comment]
What scopes are do you have in your token request? It is crashing due to `tokenInfo.scope.split(' ');` So it looks like there is no scope object getting pulled from your request. What does your tokenInfo response look like?
