### ISSUE TITLE
Create app in advance with only username and password

### ISSUE THREAD

**Issue by Tank-Missile** [not-an-aardvark/snoowrap#231]
Apps such as [RedReader](https://github.com/QuantumBadger/RedReader) create an app and authorize access with only a username and password. They do not require an app to be created beforehand. From reading over the documentation, snoowrap does not provide such functionality. snoowrap.getAuthUrl and snoowrap.fromAuthCode handles authorization in advance, but not app creation in advance.

**Comment by SpyTec** [comment]
I don't think you can create apps through the api, you'd have to go to preferences and create it there each time. Technically you can automate this with something like selenium

**Comment by NGTmeaty** [comment]
Hi! I don't believe RedReader is actually creating apps on the fly! From what I can see and [this line of code](https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/reddit/api/RedditOAuth.java#L45) they are using a hardcoded application, this is supported in snoowrap.

**Comment by Tank-Missile** [comment]
Yes, I made progress on my extension once I realized the code was hardcoded. I'll close this now.
