### ISSUE TITLE
How to get user's front page submissions

### ISSUE THREAD

**Issue by mohandeblaze** [not-an-aardvark/snoowrap#233]
I can able to get the Hot, New, Top submissions but those are all general submission even if i not logged-in i can able to get those post. But when i am authenticated my front page will curated based on my subscribed subreddits, can i get these submission using snoowrap? PRAW have something like [this](https://praw.readthedocs.io/en/latest/code_overview/reddit/front.html#). Thanks.

**Comment by SpyTec** [comment]
`getBest()` will return the frontpage https://not-an-aardvark.github.io/snoowrap/snoowrap.html#getBest__anchor

**Comment by mohandeblaze** [comment]
@SpyTec thanks for the quick reply, i could have looked at the documentation little too careful and not open this issue but i relied too much on the intellisense from d.ts and the `getBest()` API seems to be missing.

**Comment by NGTmeaty** [comment]
It exists for me. Could we see some code where you're having this issue?

Thanks.

**Comment by SpyTec** [comment]
Yeah we do not have it in TypeScript type definitions yet. I'll open another issue for it
