### ISSUE TITLE
r.getSubreddit('sub').getRandomSubmission() consistently retrieving hottest submission

### ISSUE THREAD

**Issue by mattmular** [not-an-aardvark/snoowrap#234]
`r.getSubreddit('thighdeology').getRandomSubmission().then(post => {console.log(post))};
`

This method always returns the exact same submission, which is currently the hottest submission at the time. Can't provide anymore information as that's as far as I understand.

EDIT: After investigating it seem reddit may have scrapped the subreddit/random api endpoint will update with confirmation

**Comment by SpyTec** [comment]
Seems it will always returns random from front-page. It's still in dev/api and "works" so we will not mark it as deprecated.
