### ISSUE TITLE
Publish Fixes for TypeScript 3.7 to NPM

### ISSUE THREAD

**Issue by jasonharrison** [not-an-aardvark/snoowrap#242]
snoowrap@latest (1.20.0) does not have the fixes from commit https://github.com/not-an-aardvark/snoowrap/pull/226/commits/f833017086da97525c60d386d9c38566ceef6a99.

Now that TypeScript 3.7 is released, we should publish an updated package to NPM.

**Comment by SpyTec** [comment]
Heya, this has now been published to v1.20.1 :)
