### ISSUE TITLE
upvote_ratio not on getTop Submission Array

### ISSUE THREAD

**Issue by DavidWhit** [not-an-aardvark/snoowrap#248]
Example:
`r.getSubmission("t3_9ozauu").fetch() results`
(works) upvote_ratio exits

`r.getSubreddit("ProgrammerHumor").getTop({time: "all", limit: 20})`
array of Submissions yet they are all missing upvote_ratio.

Thus, you have to call redundantly for each submission you already have.

**Comment by SpyTec** [comment]
That is how Reddit's API displays it. Only shows it in detail and not in list view
