### ISSUE TITLE
[Question] Add listener for private message replies.

### ISSUE THREAD

**Issue by IanDuncanT** [not-an-aardvark/snoowrap#253]
I currently have my bot sending several private messages and would like them all to have a listener to execute based on replies. I looked at the documentation, but couldn't find anything on replies to private messages.

**Comment by SpyTec** [comment]
Hi, there are no event streams/listeners within Snoowrap. There's an unofficial extension called SnooStorm which might help you out, otherwise you'd have to wrap it yourself
