### ISSUE TITLE
How do i get user's karma?

### ISSUE THREAD

**Issue by nikidziuba** [not-an-aardvark/snoowrap#257]
Is there anything like r.getUser('*').getKarma?

**Comment by LetsMelon** [comment]
If it is still relevant:
```js
r.getUser('not_an_aardvark').fetch().then(userInfo => {
  console.log(userInfo.awardee_karma);
  console.log(userInfo.awarder_karma);
  console.log(userInfo.link_karma,);
  console.log(userInfo.comment_karma);
});
```

Snoowrap documentation: https://not-an-aardvark.github.io/snoowrap/RedditUser.html#fetch__anchor
Reddit API: https://www.reddit.com/dev/api/#GET_user_{username}_about
