### ISSUE TITLE
error TS2304: Cannot find name 'ReadableStream'.

### ISSUE THREAD

**Issue by ihopeudie** [not-an-aardvark/snoowrap#260]
TypeScript 3.8.3:

node_modules/snoowrap/dist/objects/Subreddit.d.ts:252:18 - error TS2304: Cannot find name 'ReadableStream'.

252   file: string | ReadableStream;
                     ~~~~~~~~~~~~~~
Found 1 error.

**Comment by tantricllama** [comment]
I just ran into this. After some research I found it's referring to something in the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream).

It's defined in the lib.dom.d.ts, so you need to make sure that lib is included in the compilerOptions:

```
{
  "compilerOptions": {
    "lib": [
	  "dom",
      "es6"
    ],
	...
}
```
