### ISSUE TITLE
How to get more than 1000 listings?

### ISSUE THREAD

**Issue by timendez** [not-an-aardvark/snoowrap#275]
Hi there, I have the following code:

```javascript
let topPosts = await r.getSubreddit('aww').getTop({ limit: 10000, time: 'all' });
for (let i = 0; i < 10; i++) {
    const extended = await topPosts.fetchMore({ amount: 5000, append: true });
    console.log(extended.length);
    if (extended.isFinished) {
        console.log('finished early');
        break;
    }
}
console.log(`/r/aww has ${topPosts.length} posts`);
```

`isFinished` is true at that point.

`topPosts`'s length is 1000, and `extended`'s length is also 1000.

My ultimate goal is to get about 10k listings of a subreddit sorted by top - perhaps I'm just not iterating through it properly, or is 1000 the limit?

Thanks!

**Comment by timendez** [comment]
Additionally, if I set `limit` to 500 and `amount` to 200, then `extended`'s length **is** 700, which leads me to believe that this is a Reddit API limit of 1000 listings

**Comment by SpyTec** [comment]
Yes, Reddit does limit to around 1000 posts and comments. I'm not sure but [PushShift](https://pushshift.io/) might be better off in your use-case, though I've never used it

**Comment by timendez** [comment]
Thank you @SpyTec! I didn't know about PushShift before, and you're right, it's exactly what I needed. I'm now using a combination of snoowrap and PushShift
