### ISSUE TITLE
getContentByIds method missing from typescript definitions

### ISSUE THREAD

**Issue by mmahandev** [not-an-aardvark/snoowrap#286]
`getContentByIds` method missing from the typescript definitions.

Anyone know how I can temporarily add this to my project?

**Comment by hmble** [comment]
I guess we can add something like after line
https://github.com/not-an-aardvark/snoowrap/blob/da759f8b082ce53bf838d680711dd9b1ad693b1d/src/snoowrap.d.ts#L82

```js
getContentByIds(ids: Array<_Submission | _Comment | string>) : Promise<_Listing<_Submission | _Comment>>;
```

This definition is taken from [snoowrap.js#L865](https://github.com/not-an-aardvark/snoowrap/blob/f2ca3871963dbc7832800f1883b5359a7c72d4a5/src/snoowrap.js#L865).

I don't know much on how type definitions work, I figured this one by looking on other type definitions. I can make PR for this if its right.
