### ISSUE TITLE
TypeScript & SubmitSelfPost

### ISSUE THREAD

**Issue by MercerK** [not-an-aardvark/snoowrap#291]
I ran into a bug with `submitSelfPost` for Subreddit. The documentation states to use `submitSelfpost` (lowercase P) however TypeScript autocorrects to `SubmitSelfPost` (with uppercase P). 

* Using `submitSelfPost` returns an error.
* Using `submitSelfpost` does not return an error.

**Comment by SpyTec** [comment]
Thanks, I've gone ahead and fixed that. Until we get a new release simply add a TypeScript ignore comment on it
