### ISSUE TITLE
Get submission id from nested comment

### ISSUE THREAD

**Issue by Chaphasilor** [not-an-aardvark/snoowrap#302]
I have an arbitrary comment, could be top level or nested.  
What I want is to get the id of the submission this comment belongs to.

Sadly, `parent_id` only returns the id of the nearest parent, so a reply to comment X will have a `parent_id` equal to the id of comment X.  

Is there a way to get the submission id, other than traversing the comment tree to the top?  
Something like `Comment.submission_id` that always points to the submission?

**Comment by SpyTec** [comment]
A good tip for finding out what attributes are exists for Subreddits, Submissions, and Comments is to add `.json` to a normal Reddit URL: https://www.reddit.com/r/programming/comments/km3pke/nodeexamplecom_is_an_ip_address/ghcs2tj/.json

---

To answer your question, seems like `link_id` is what you're looking for

**Comment by Chaphasilor** [comment]
Hmm, I already did log the object and took a look at it. `link_id` was `null`, for some reason.

I got the comment by retrieving my inbox (only username mentions).

**Comment by SpyTec** [comment]
I see.. may just be that you have to parse `context` to get the submission ID, otherwise I'd ask in r/redditdev subreddit

**Comment by Chaphasilor** [comment]
> may just be that you have to parse `context` to get the submission ID 

yeah, thought as much. that's the only place I found the submission id. I'm simply looking for a more elegant solution \^\^ 

I'll ask on reddit, thanks for you help :D
