### ISSUE TITLE
Any way to get more than 25 results from Subreddit.search?

### ISSUE THREAD

**Issue by Wayne-Ennis** [not-an-aardvark/snoowrap#307]
Hi,
is there anyway to pass in parameters for pagination?  i'm looking to process more than 25 results.  should i be using another object?

### What i've tried
  - I notice that i do get the same exact set in results

```js

var resp = await client.search({query: 'xxx', subreddit: 'yyy', time: 'day', sort: 'new'});

var resp = await (await client.getSubreddit('yyy')).search({query: 'xxx', time: 'day', sort: 'new'});
```
thanks

**Comment by Wayne-Ennis** [comment]
stumbled upon fetchAll method

**Comment by ralyodio** [comment]
how do i use?
