### ISSUE TITLE
snoowrap does not work in mobile browsers

### ISSUE THREAD

**Issue by not-an-aardvark** [not-an-aardvark/snoowrap#33]
(Continued from #32)

Browsers don't allow custom user-agent headers to be set in XHR requests. This is apparently causing some issues with clients being redirected to reddit's mobile site.

It seems to only cause issues on mobile browsers; while the user-agent can't be set in desktop browsers either, reddit seems to work fine with the default user-agent there.

**Comment by mschwartz** [comment]
+1

**Comment by mschwartz** [comment]
BTW, I'm a framework engineer at Sencha.

**Comment by not-an-aardvark** [comment]
Should be fixed in v1.6.0.
