### ISSUE TITLE
content_md returning 'undefined' when attempting to print wiki page

### ISSUE THREAD

**Issue by PictureGamer** [not-an-aardvark/snoowrap#34]
Even with mod permissions for my subreddit's wiki page, I'm unable to read the content of our Wiki page

**Comment by not-an-aardvark** [comment]
Thanks for the bug report. Could you show me the code that's causing the issue?

**Comment by PictureGamer** [comment]
Sure, the running code is:

```
const snoowrap = require('snoowrap');
const AuthDetails = require("./auth.json");

const r = new snoowrap({
  user_agent: AuthDetails.user_agent,
  client_id: AuthDetails.client_id,
  client_secret: AuthDetails.client_secret,
  username: AuthDetails.username,
  password: AuthDetails.password
});

r.get_subreddit('PictureGame').get_wiki_page('leaderboard').content_md.then(console.log);
```

And the error I receive is:

```
r.get_subreddit('PictureGame').get_wiki_page('leaderboard').content_md.then(console.log);
                                                                      ^

TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/Users/XXX/Desktop/DiscordBotCopy/redditauth.js:11:71)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

The other Wiki functions seem to operate properly however, i.e. "get_settings()" works just fine for me

**Comment by not-an-aardvark** [comment]
I see. What version of Node.js are you using?

If you're using Node 5 or below, then snoowrap's method chaining won't be enabled (see the [section in the readme](/not-an-aardvark/snoowrap#important-note-on-es6) for more details). Basically, accessing the `content_md` property can only return a Promise if the current runtime supports the `Proxy` object.

To get around this issue, you can fetch the wiki page manually:

```js
r.get_subreddit('PictureGame').get_wiki_page('leaderboard').fetch().then(function(page) {
  console.log(page.content_md);
});
```

**Comment by PictureGamer** [comment]
Ahh so obvious now, thank you! I thought I was running 6.3.1 but looks as if I'm still on 4.4.7. The manual fetch works great
