### ISSUE TITLE
NoCredentialsError: Missing credentials passed to snoowrap constructor

### ISSUE THREAD

**Issue by pgiro** [not-an-aardvark/snoowrap#356]
I have been using snoowrap for about half a year with no issue, when today my code refused to compile due to the below error

NoCredentialsError: Missing credentials passed to snoowrap constructor. You must pass an object containing either (a) userAgent, clientId, clientSecret, and refreshToken properties, (b) userAgent and accessToken properties, or (c) userAgent, clientId, clientSecret, username, and password properties. For information, 
please read the docs at https://not-an-aardvark.github.io/snoowrap/.

Which is confusing because (1) it worked before and (2) I am passing an object with userAgent, clientId, clientSecret and refreshToken to the constructor like so (have also tried newing up 'Snoowrap' instead of 'snoowrap')

```js
const redditRequestor: Snoowrap = new snoowrap({
  userAgent: 'User Agent Name',
  clientId: process.env.REDDIT_CLIENT_ID,
  clientSecret: process.env.REDDIT_CLIENT_SECRET,
  refreshToken: process.env.REDDIT_REFRESH_TOKEN
})
```

**Comment by Venefilyn** [comment]
If nothing has changed with the constructor code, have you checked the env values?

**Comment by pgiro** [comment]
In the least satisfying of possibilities, it compiles today no problem... Not sure what the issue was but will close
