### ISSUE TITLE
Search inbox

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#42]
Is there a way to search my inbox? including both my user inbox and mod messages?

**Comment by not-an-aardvark** [comment]
Not really, no. This module is only a wrapper around reddit's API, and reddit's API doesn't expose an inbox search function.

As a workaround, I suppose you could fetch the most recent messages in your inbox or modmail (e.g. with [getInbox](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#getInbox__anchor)) and then do a regex search on the result.

**Comment by not-an-aardvark** [comment]
Going to close this issue, but feel free to continue the discussion if you have any more questions.
