### ISSUE TITLE
Send private message?

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#43]
Is it possible to send a private message to a user?
If not, is there anyway to customize the email sent when you approve a user to a private subreddit?

**Comment by not-an-aardvark** [comment]
Thanks for the question. You can use [composeMessage](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#composeMessage__anchor) to send a private message to a user.

**Comment by chovy** [comment]
oh dang. i searched for sendMessage and newMessage

it would be nice if i could see the entire docs on one page so i can search it better.

**Comment by sam-hajj** [comment]
For some things docs are still not the easiest to parse, it would be nice to have a link to the composeMessage method in the doc page of the [PrivateMessage](https://not-an-aardvark.github.io/snoowrap/PrivateMessage.html) class. It may reduce confusion especially for newer users
