### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by noahluddy** [not-an-aardvark/snoowrap#45]
I'm trying to use snoowrap in the browser, but I keep getting a 403 error. 

I created a reddit app and used reddit-oauth-helper to get a refresh token. In my code on my machine, I have my clientId, clientSecret, and refreshToken actually typed in. I just replaced them in the picture with my__isHere. 

I've tried two separate sets of credentials, one for a web app and one for a script. 

Also, I do plan to link to the minified version of snoowrap in the end, but I linked to the full version here to show what lines in the source code exactly are raising the error. 

Thank you for your help. 

PS: I am also curious why a clientID, clientSecret, and refreshToken are needed in snoowrap. I've used praw (python reddit api wrapper) before and it doesn't require any OAuth credentials, only a user_agent. Regardless, thank you again for your help. 

<img width="829" alt="code" src="https://cloud.githubusercontent.com/assets/22121182/18979368/dccb3ace-868f-11e6-9838-c42d790bae33.png">

<img width="919" alt="error" src="https://cloud.githubusercontent.com/assets/22121182/18979132/e0bb66c4-868d-11e6-85d2-747152325d82.png">

**Comment by not-an-aardvark** [comment]
Thanks for the issue.

When you used reddit-oauth-helper to generate a token, what scope did the token have? I think getting posts from the front page requires `read` scope, so if your token doesn't have that reddit will throw a 403 error. (Admittedly, snoowrap should probably document the concept of scope better than it currently does.)

To answer your other question: I haven't looked into how PRAW does it, but I assume it's using something like [Application Only OAuth](https://github.com/reddit/reddit/wiki/OAuth2#application-only-oauth). Snoowrap doesn't support that at the moment (although there's not really any good reason why it shouldn't -- I'll look into adding it).

**Comment by noahluddy** [comment]
I chose the 'vote' scope for the first set of credentials and 'identity' scope for the second set.

**Comment by not-an-aardvark** [comment]
I see, that's probably the issue then. If you select the `read` scope as well (you can select multiple scopes for a token), I think the problem should go away.

**Comment by noahluddy** [comment]
It worked! Thank you so much for your help.
