### ISSUE TITLE
only reply to comment if no other comment has been made

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#47]
I want to create a bot that replies to a comment in a thread but only if my bot has not already commented in any other comment for that post.

What's the easiest way to do this? do I need to keep track of threads it has posted in in a local database?

**Comment by not-an-aardvark** [comment]
Using a local database would be one solution. Alternatively, you could:

* Look at the other comments on the thread to see if any of them were made by your bot (might cause problems if the threads are very large)
* Look at your bot's user history to try to find a comment on the given thread (might cause problems if your bot makes comments very frequently)

I think a local database would probably be the best solution, if it's feasible for what you're trying to do.
