### ISSUE TITLE
make a post/submission?

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#49]
Not knocking the project but those docs  I can't never find anything by searching.

How do I make a submission to a sub reddit? Which class would that be under?

edit: i found it.

**Comment by not-an-aardvark** [comment]
For anyone reading this in the future, the functions are [submitSelfpost](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#submitSelfpost__anchor) and [submitLink](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#submitLink__anchor).

Thanks for the feedback on the docs! I've been meaning to redo the layout of the docs, but I haven't found anything that works as I want it to yet. (At the moment, the docs are automatically generated from inline comments, which means I don't have to maintain them separately. I use [ink-docstrap](https://github.com/docstrap/docstrap) for this. I've considered using other JSDoc plugins which would allow everything to appear on the same page, but none of them seem to have the features that ink-docstrap has (e.g. putting a script tag at the bottom of the page to allow the library to be used in the console).

**Comment by chovy** [comment]
yeah. the docs are actually quite good but there's no way to search. Have you looked at readme.io? I think its free for open source. Basically turns your markdown docs into a nice looking html.

But really I just want to see everything in one page so I can do `ctrl+f` and find what I'm looking for. The current search only seems to search class name or something. Not sure what. Like "create post" and "submit post" didn't come up with anything.
