### ISSUE TITLE
Not collecting more than 1000 listings?

### ISSUE THREAD

**Issue by NathanAB** [not-an-aardvark/snoowrap#51]
Not sure if this is a bug or what, but after 1000 listings have been collected for a certain call, the queries stop. For example, if I try to request the top 2000 listings in /r/learnprogramming, I see this in debug mode:

```[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=2000. ratelimitRemaining: 599
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1900&after=t3_4d1etw. ratelimitRemaining: 598
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1800&after=t3_4ckgb4. ratelimitRemaining: 597
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1700&after=t3_3v17bs. ratelimitRemaining: 596
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1600&after=t3_3pjrqc. ratelimitRemaining: 595
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1500&after=t3_52h90d. ratelimitRemaining: 594
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1400&after=t3_4lwus2. ratelimitRemaining: 593
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1300&after=t3_4b49co. ratelimitRemaining: 592
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1200&after=t3_3w4vzw. ratelimitRemaining: 591
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1100&after=t3_52o33q. ratelimitRemaining: 590
[debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/learnprogramming/top?raw_json=1&count=9999&limit=1000&after=t3_4256ur. ratelimitRemaining: 589```

And then it just stops. As you can see, the `limit` param is still at 1000, meaning there are 1000 more listings that I still have not received. Digging into the code I found that the `query.after` value was not being set on the last call which caused the queries to stop, however I'm not sure what exactly that implies. Am I missing something here?

**Comment by not-an-aardvark** [comment]
Thanks for the report. I'm pretty sure this is actually a limitation of reddit's API; it only allows pagination up to a certain point, and after that it no longer allows you to view more pages (although it still allows you to view submissions if you have the permalink).

As a demo of the usual pagination behavior, see this link: https://www.reddit.com/r/learnprogramming/top.json?limit=1&t=all

Note that there are keys for `"after": "t3_4q6tae", "before": null`. (This is the top post on the front page of the sub, so the ID might be different if a new post reaches the top.) This indicates that in the next request, you can add that as a querystring param to get the next results:

https://<span></span>www.reddit.com/r/learnprogramming/top.json?limit=1&t=all**&after=t3_4q6tae**

That will return another response with an `after` key, and so on. However, once you get past a certain point, reddit returns `after: null`. At this point, you can't fetch anything else (putting an `after` param there manually yields an empty response like [this](https://www.reddit.com/r/learnprogramming/top.json?raw_json=1&count=9999&limit=1000&after=t3_4256ur)), so snoowrap [stops fetching things](/not-an-aardvark/snoowrap/blob/1110f45a1596beb2fc2ab2d0eee81b1f991f5b29/src/objects/Listing.js#L80-L86) and returns all the submissions that it has accumulated so far.

**Comment by NathanAB** [comment]
Awesome explanation, thank you @not-an-aardvark. Shame that we are limited in this way...I was hoping to grab a huge dataset to use for some ML fun. Oh well, I guess there is nothing that can really be done about it then :(

**Comment by chovy** [comment]
@NathanAB you can always get it by scraping.

**Comment by not-an-aardvark** [comment]
I'm going to close this issue since it seems to be resolved, but feel free to continue the discussion.
