### ISSUE TITLE
r.getHot() returns HTML

### ISSUE THREAD

**Issue by benwaffle** [not-an-aardvark/snoowrap#52]
```javascript
r.getHot().then(console.log)
```

**Comment by not-an-aardvark** [comment]
I can't reproduce this; it does not return HTML for me. Could you provide more details?

**Comment by benwaffle** [comment]
main.js:
```javascript
'use strict'

const snoowrap = require('snoowrap')

const r = new snoowrap(require('./config.js'))

r.getHot().then(console.log)
```

config.js:
```javascript
module.exports = {
    userAgent: 'best-comments-reader',
    accessToken: 'my-access-token',
}
```

I got the accesstoken by creating an app in https://www.reddit.com/prefs/apps and copying the value next to 'secret'

**Comment by not-an-aardvark** [comment]
I see; the issue is that your access token is invalid, so reddit is returning the HTML of its error page.

The "secret" value on reddit.com/prefs/apps is a *client secret*, not an access token. For more info on the distinction (and how to create an access token), I would recommend looking at [reddit-oauth-helper](https://github.com/not-an-aardvark/reddit-oauth-helper).

**Comment by benwaffle** [comment]
alright. it would be nice if snoowrap could detect these errors

**Comment by benwaffle** [comment]
Are these the correct fields to use in the config?

![r](https://cloud.githubusercontent.com/assets/1713819/20240934/ceaced4e-a8f3-11e6-9190-ed0b5ea5abda.png)

![screenshot from 2016-11-12 16-13-48](https://cloud.githubusercontent.com/assets/1713819/20240936/d467ff8a-a8f3-11e6-8e34-4501be7dbc1e.png)

**Comment by not-an-aardvark** [comment]
Yes, those are the correct values.

It's possible to make unauthenticated requests ([Application Only OAuth](https://github.com/reddit/reddit/wiki/OAuth2#application-only-oauth)), but there are a few caveats:

* snoowrap doesn't support this at the moment, unfortunately.
* [Apparently there are some issues with getting Application Only OAuth to work in browsers.](https://github.com/reddit/reddit/issues/1285) (Based on that link, it looks like maybe the issues have been fixed, but I'm not sure.)

I'm not sure what your use-case is, but if you want the user to be able to authenticate with their own account (e.g. in a browser), you can use [snoowrap.getAuthUrl](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#.getAuthUrl) and [snoowrap.fromAuthCode](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#.fromAuthCode) to go through the same process as what reddit-oauth-helper did.

**Comment by benwaffle** [comment]
Hmm, now i'm getting `Unhandled rejection StatusCodeError: 403 - {"message":"Forbidden","error":403}`

**Comment by not-an-aardvark** [comment]
What did you select for the `scope` of your token?

**Comment by benwaffle** [comment]
identity

**Comment by not-an-aardvark** [comment]
In order to get posts from the front page, you need the `read` scope ("Access posts and comments through my account").

**Comment by benwaffle** [comment]
awesome! thanks
