### ISSUE TITLE
submitSelfpost() returning incorrect/incomplete data

### ISSUE THREAD

**Issue by LukeNZ** [not-an-aardvark/snoowrap#55]
Is there something incorrect I'm doing here? When I submit a selfpost, the promise that is returned by snoowrap only resolves to a `Submission` object with a single key: 'name':

            this.r.getSubreddit('mysub').submitSelfpost({
                title: "foo",
                text: "bar",
                sendReplies: false
            }).then(console.log);

            // console.log outputs: Submission { name: 't3_threadid' }

 The title or any other parameters of the thread are not returned, which is in conflict with the documentation here: https://not-an-aardvark.github.io/snoowrap/Subreddit.html#submitSelfpost__anchor

Which clearly shows a Submission object being returned with, among other things, a title. 

Using snoowrap 1.11.3 and Node 7.2.1.

**Comment by not-an-aardvark** [comment]
I think this is working as intended, but it looks like the docs are wrong. The API endpoint for submitting a post only returns the ID of the post, without any other information on it.

As a workaround, you can use:

```js
        this.r.getSubreddit('mysub').submitSelfpost({
            title: "foo",
            text: "bar",
            sendReplies: false
        }).then(submission => submission.fetch())
          .then(console.log);
```

**Comment by LukeNZ** [comment]
Ahh, that makes more sense. Cheers.
