### ISSUE TITLE
How to expand a particular comment's replies?

### ISSUE THREAD

**Issue by ucarion** [not-an-aardvark/snoowrap#59]
Context: I'm writing a Reddit client. I want to re-implement the "load more comments" button.

Suppose I get a submission's comments tree via `r.getSubmission('...').comments`. Is there a way to get a new version of that comments tree, with a particular "More" node expanded?

**Comment by not-an-aardvark** [comment]
If you have a particular comment object, you can use

```js
comment.replies.fetchMore({ amount: 10 }) // e.g. fetch 10 reply chains

// or

comment.replies.fetchAll() // fetch all reply chains
```

This will return a Promise for a Listing containing replies.

If you want a new version of the comments tree with all replies, you can use [comment.expandReplies](https://not-an-aardvark.github.io/snoowrap/Comment.html#expandReplies__anchor) and optionally specify a depth limit.

**Comment by ucarion** [comment]
Are you saying there isn't a built-in way to directly emulate the "load more comments" button?

I realize that what I'm asking for doesn't directly correspond to an API endpoint -- it's the combination of `/api/morechildren` and putting the result back into the complete comments tree. I think I see how I could implement this myself, but maybe it'd be appropriate to implement this in Snoowrap directly, since it corresponds to an action the reddit.com UI provides, and that basically every Reddit client needs?

**Comment by not-an-aardvark** [comment]
If I'm understanding your question correctly, [expandReplies](https://not-an-aardvark.github.io/snoowrap/Comment.html#expandReplies__anchor) mostly does what you're looking for. The only difference is that a new comment object is returned rather than changing the existing comment object.

In general, snoowrap's objects are treated as immutable (all of snoowrap's methods create new objects rather than mutating existing objects). If you need a mutable data structure, you could try:

* Creating a mutable wrapper that gets data from a snoowrap object
* Changing the properties of snoowrap objects yourself. (None of snoowrap's internal methods mutate snoowrap objects, but they're not actually frozen. I think everything would still work if you did something like `comment.replies = await comment.replies.fetchAll()`.)

**Comment by ucarion** [comment]
It took a bit of re-writing, but I've updated my code to have easy access to `comment.replies` for all comments, and I'm now using `fetchMore` to get more replies. I'm not sure if I understand the code for `Listing`, but it seems I should be passing `amount: Infinity` to reproduce Reddit's behavior?

Btw, Snoowrap's immutability is a huge feature for me. I'm using Snoowrap in a Redux application, and if things were mutable I wouldn't be able to use this library.

However, I still think my original question remains unanswered. You know what I mean when I'm talking about reproducing the behavior of the "load more comments" button, right? I want to get back a comments tree that is a clone of the first one, except one of the comments (whose id is given as an argument) will now have more replies. I don't see how I could express that using `expandReplies`, since it takes `depth` and `limit`, which don't have anything to do with the behavior I want.

**Comment by not-an-aardvark** [comment]
I think the "load more comments" button on reddit always sends exactly one request to the `api/morechildren` endpoint, and displays whatever the reddit API returns. Reddit's response to this endpoint is somewhat inconsistent (e.g. it won't always return all of the requested replies to a comment if the reply trees are too large). Snoowrap wraps this behavior to be more consistent (for example, if you request 30 more replies, snoowrap will return 30 more replies even if it takes more than one request to retrieve all of them).

At the moment, I don't think there is any way to directly mirror the single-request behavior, but you can get a close approximation with

```js
comment.replies.fetchMore({ amount: 20 });
```

This will always get exactly 20 more replies (or all the remaining replies, if there are fewer than 20 left). In most cases this is the same as the html site behavior, with the caveat that it will sometimes send multiple requests to retrieve 20 replies in cases where the html site would retrieve fewer than 20 replies.

**Comment by ucarion** [comment]
That's not ideal, but I see why Snoowrap does that. I guess I'm actually interested in preserving Reddit's quirky behavior, since it makes sense for a Reddit UI.

I guess I'm gonna close this issue, because "load more comments" behavior is a very UI-specific thing and Snoowrap doesn't really work that way. Ultimately, I suspect I'll need to fork Snoowrap or maybe add my own abstraction over Snoocore, because I think I want this feature.

**Comment by Andrew213** [comment]
prisoyedinyayus' k obsuzhdeniyu. Spustya bol'shoye kolichestvo vremeni yeshche ne reshena problema. Mne takzhe nuzhno povedeniye Bol'she kommentariyev.

No vopros v tom - Kak mne iznachal'no poluchit' nuzhnoye kolichestvo kommentariyev?
I join the discussion. After a lot of time, the problem has not yet been resolved. I also need the behavior More comments.

But the question is - How do I get the desired number of comments initially?

**Comment by Andrew213** [comment]
I join the discussion. After a lot of time, the problem has not yet been resolved. I also need the behavior More comments.

But the question is - How do I get the desired number of comments initially?

For example, first display 10 comments, then another 10 including replays
