### ISSUE TITLE
filter results for offsite links?

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#64]
Is it possible to search reddit for offsite links? typically these would mean just searching title and that its a link submission.

for example I don't want results to contain links back to reddit text posts.

**Comment by TheAppleFreak** [comment]
If I'm understanding this correctly, you don't want any submissions in a stream of new posts to contain links to other posts on Reddit, right? If so, [I wrote a set of regular expressions to detect links to other Reddit threads](https://www.reddit.com/r/modclub/comments/4vaqiw/need_to_filter_links_to_reddit_threads_heres_the/) (we've been using it on PCMR for 6-7 months and have had only one false positive so far). You'd want to use the full link filter with hostnames in this case. Note that this was written for Python's `regex` module, so you'd have to make sure it works with Javascript's regex engine first. 

If you're using Reddit's search functionality to find link posts, include `self:no` in the search query to exclude self posts, then use the regex above to find links to Reddit threads.

**Comment by not-an-aardvark** [comment]
I think you might also be able to use the `domain:` search filter:

```
NOT domain:reddit.com
```

By the way, for questions that are just about reddit rather than about snoowrap, you might get better responses if you ask on /r/redditdev instead.

**Comment by chovy** [comment]
fyi passing `type: 'link'` works
