### ISSUE TITLE
override rawRequest seems to take 3x longer

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#66]
```
class SnoowrapWithProxy extends Snoowrap {
  rawRequest(options) {
    return request(Object.assign(options, {}));
  }
}
```

If I use this method it seems api queries (`search` in this case) take 30 seconds or so to return. With out the rawRequest override they take 10s which still seems like a long time for an api call. Is this just due to reddit's slowness?

I'm just making the one api call so I shouldn't be rate-limited that i am aware of.

Here are the options:

```
    const params = {
      query: `${this.opts.query}`,
      time: 'all',
      sort: 'hot',
      limit: 100
    };
    const data = await this.client.search(params);
```

If I set limit to 10 its pretty quick (5s or so) but that still seems like a lot.

**Comment by not-an-aardvark** [comment]
It's possible this is happening because the default `rawRequest` function enables gzip compression. What happens if you replace your class with this?

```js
class SnoowrapWithProxy extends Snoowrap {
  rawRequest(options) {
    return request(Object.assign(options, { gzip: true }));
  }
}
```

> With out the rawRequest override they take 10s which still seems like a long time for an api call. Is this just due to reddit's slowness?

I think so -- it does have to send you a significant amount of data from 100 posts. Your internet connection might also be a factor.

**Comment by chovy** [comment]
it has to be reddit's servers. I am hitting youtube and twitter and getting 100 objects back for each and I hit each of them 3x each in my test sweet. still does 6 api calls on yt/tw in less than 3 seconds.

one reddit api call takes 7-10 seconds (even with gzip)

**Comment by not-an-aardvark** [comment]
I don't understand the question.

**Comment by chovy** [comment]
I'm asking if you're paginating via queries....for example in a loop getting 10 at a time until 100 is reached. Or do you make one query and pass the size to reddit's api.

That's the only that would explain this huge delay.

**Comment by not-an-aardvark** [comment]
Generally, it tries to minimize the number of queries.

You can view each request that gets sent with

```js
r.config({ debug: true });
```

**Comment by chovy** [comment]
`https://oauth.reddit.com/search?raw_json=1&count=9999&sort=hot&limit=100&restrictSr=true&syntax=plain&t=day&q=javascript&restrict_sr=true.`

why is `count` set to `9999`? I don't know if that will slow it down but it definitely explain it. I am however only getting 100 results back in the data that is returned to me. But if you fetch 10k items. that is going to slow it down.

**Comment by not-an-aardvark** [comment]
`count` is unrelated -- it's used to ensure pagination works, and a large value doesn't slow down the request. `limit` is the number of items being fetched.

**Comment by not-an-aardvark** [comment]
I tried this out myself -- it looks like the same issue happens when curl is used to fetch the results instead of snoowrap. So I think you're right that this is due to the reddit servers.

**Comment by chovy** [comment]
I see. changing it didn't make any noticable difference. I need to set my test to 10 seconds plus. Is that normal from your experience?

You can see my query right there...anything that would be slowing it down?

**Comment by chovy** [comment]
edit: i see your reply. I wonder if you do some kind of autorecovery where if you get the typical reddit 500 it retries?

**Comment by not-an-aardvark** [comment]
Yes, snoowrap retries requests up to a maximum of 3 times if it receives a 503 error.

> how do i do a curl query by the way?

```bash
curl -H 'Authorization: bearer <an access token>' -H 'User-Agent: search test' 'https://oauth.reddit.com/search?raw_json=1&count=9999&sort=hot&limit=100&restrictSr=true&syntax=plain&t=day&q=javascript&restrict_sr=true'
```

**Comment by chovy** [comment]
can i get the token from the snoowrap instance I'm using?

**Comment by not-an-aardvark** [comment]
Yes, use `r.accessToken` (after sending a request).

Since this isn't an issue with snoowrap, I'm closing this issue.
