### ISSUE TITLE
getSubmissions() returns an HTML string when unauthenticated, instead of a Listing.

### ISSUE THREAD

**Issue by MeLlamoPablo** [not-an-aardvark/snoowrap#73]
Hello! This is probably related to #72.

I'm getting started with the Reddit API and I'm currently experimenting. I fucked up with my password variable, which led to making a request while unauthenticated. That request returned a string of the HTML equivalent of visiting `https://www.reddit.com/user/<username>/submitted/`. However, when authenticated, it did return the Listing, as expected.

Now, as I said I'm new to this so maybe I'm wrong, but wouldn't that still be a valid request, since the information is public? The way I see it, it should return a Listing even unauthenticated, or reject the Promise, but not return HTML.

Here's the code that works:

```js
"use strict";

const snoowrap = require("snoowrap");

async function main() {

    let reddit = new snoowrap({
        userAgent: "Test app by /u/sfcpfc",
        clientId: process.env.CLIENT_ID,
        clientSecret: process.env.CLIENT_SECRET,
        username: process.env.USERNAME,
        password: process.env.PASSWORD
    });

    let submissions = await reddit.getUser("sfcpfc").getSubmissions();

    console.log(submissions); // Logs the Listing as expected

}

main().catch(console.error);
```

Here's the code that doesn't:

```js
"use strict";

const snoowrap = require("snoowrap");

async function main() {

    let reddit = new snoowrap({
        userAgent: "Test app by /u/sfcpfc",
        clientId: process.env.CLIENT_ID,
        clientSecret: process.env.CLIENT_SECRET,
        username: process.env.USERNAME,
        password: "somerandomstring" //process.env.PASSWORD
    });

    let submissions = await reddit.getUser("sfcpfc").getSubmissions();

    console.log(submissions); // Logs HTML containing my submissions

}

main().catch(console.error);
```

**Comment by not-an-aardvark** [comment]
I can't reproduce this issue -- I get the error described in https://github.com/not-an-aardvark/snoowrap/issues/72 when I try this, not an HTML response.

**Comment by MeLlamoPablo** [comment]
Weird, I'm getting the same result as well now. Could be a problem that the Reddit API had, but then fixed? I guess I should close this then, unless the issue pops up again. I'll make sure to investigate further the cause if it happens.

**Comment by intergleam** [comment]
I am getting HTML as well

**Comment by vitosamson** [comment]
I'm seeing this occur when I only provide an `accessToken` (with only the `identity` scope) to the snoowrap constructor. It seems like the `/user/:user/comments` endpoint behaves differently depending on the access token provided.

This is reproducible by hitting the reddit api directly with different access tokens:
  - With an access token with just the `identity` scope, `/comments` returns HTML. Hitting `/comments.json` returns the appropriate Listing json.
  - With `clientId`, `clientSecret`, etc from a personal use script, `/comments` returns the appropriate Listing json.

This could perhaps be resolved by appending `.json` to the uri in `snoowrap._getListing`, depending on the auth options passed to the constructor?

**Comment by not-an-aardvark** [comment]
I think this is an issue with the reddit API -- some errors are returned as html. Note that with `identity` scope, you can't access `/comments` anyway, even wothout snoowrap.

**Comment by vitosamson** [comment]
Hmm yeah you're right. I was hitting the `/comments.json` endpoint from `reddit.com`, not `oauth.reddit.com`. Hitting the oauth endpoint with an `identity` token returns 403.

> I think this is an issue with the reddit API

Shocking 😄
