### ISSUE TITLE
.upvote() returns 403

### ISSUE THREAD

**Issue by neilgandhi95** [not-an-aardvark/snoowrap#79]
I added in the client key
```
const r = new snoowrap({
  userAgent: 'ua',
  clientId: 'id',
  clientSecret: 'secret',
  refreshToken: 'token'
});

```
and did 
`r.getSubmission('4e62ml').upvote()`

but i get the error of:
`Unhandled rejection StatusCodeError: 403 - {"message":"Forbidden","error":403}`

**Comment by not-an-aardvark** [comment]
I can't reproduce this issue. Are you sure your tokens are valid and your refresh token has the `vote` scope?
