### ISSUE TITLE
Ratelimit not being handled correctly?

### ISSUE THREAD

**Issue by TheHolyWaffle** [not-an-aardvark/snoowrap#81]
So I use `username` and `password to authenticate`:
```
this._r = new Snoowrap({
    userAgent: '...',
    clientId: '...',
    clientSecret: '...',
    username: '...',
    password: '...'
});
```

So I basically calll getNew at a certain interval to fetch the new submissions and if the conditions are met then I will also reply to that submission:

```
 this._r.getNew(subreddit).then(function(submissions) {
     _.each(submissions, function(submission) {
         if (.....) {
             submission.reply(text);
         }
     });
 });
```

And for some reason I get Ratelimit errors after a while:
```
May 09 15:49:13 twitch-mirrorer app/web.1:  Unhandled rejection Error: RATELIMIT,je doet dat te veel, probeer het over 3 minuten opnieuw.,ratelimit 
May 09 15:49:13 twitch-mirrorer app/web.1:      at /app/node_modules/snoowrap/dist/helpers.js:111:11 
May 09 15:49:13 twitch-mirrorer app/web.1:      at PassThroughHandlerContext.finallyHandler (/app/node_modules/bluebird/js/release/finally.js:57:23) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at PassThroughHandlerContext.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at runCallback (timers.js:672:20) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at tryOnImmediate (timers.js:645:5) 
May 09 15:49:13 twitch-mirrorer app/web.1:      at processImmediate [as _immediateCallback] (timers.js:617:5) 
```

Did I assume wrongly that the API would handle the rate limit correctly and prevent sending requests when the rate limit has been reached?

**Comment by not-an-aardvark** [comment]
You can set a request delay to enforce the ratelimit:

```js
r.config({ requestDelay: 1000 });
```

See the [config docs](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#config__anchor) for more information.

**Comment by TheHolyWaffle** [comment]
In reality, my bot only posts a new comment every 5 minutes or so. This should be way lower than the allowed rate limit? How would this extra second help me not reach the limit?

**Comment by not-an-aardvark** [comment]
Actually, I realized my first comment was incorrect -- that error isn't coming from the normal ratelimit of 600 requests per second. Reddit prevents accounts with low karma from posting too frequently, to deter spam. (You'll notice this if you try to post comments too frequently from a new account, regardless of whether you're using the API.) If you get some karma on your bot's account, I think the posting limit will go away.

**Comment by TheHolyWaffle** [comment]
Alright, for now I've also added continueAfterRatelimitError: true to the config. Would that help a bit?

**Comment by not-an-aardvark** [comment]
No, this that won't help in this case -- the continueAfterRatelimitError option only applies to the normal ratelimit of 600 requests per 10 minutes. It doesn't apply to this type of ratelimiting.

**Comment by TheHolyWaffle** [comment]
I guess that clears it all up. Thank you for the quick help :)
