### ISSUE TITLE
Subreddit .getSettings() and .editSettings() both returns a 404 error

### ISSUE THREAD

**Issue by sambunting** [not-an-aardvark/snoowrap#82]
I can't seem to figure out why but whenever I try and get the settings or edit the settings of a subreddit, it returns a 404 error. Both are showing the same error of:

    Unhandled rejection StatusCodeError: 404 - {"message":"Not Found","error":404}
    at new StatusCodeError (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\request-promise\lib\errors.js:32:15)
    at C:\Users\Sam Bunting\Documents\node.js\football\node_modules\request-promise\lib\rp.js:70:37
    at tryCatcher (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Sam Bunting\Documents\node.js\football\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

My code is as follows: 

    // Get subreddit settings. 
    reddit.getSubreddit('subreddit').getSettings().then(console.log)

    // Eddit subreddit settings
    reddit.getSubreddit('subreddit').editSettings({
        title: 'Subreddit Title', 
        public_description: 'Subreddit Description', 
        description: 'Sidebar content'
    })

Is this a bug? Or is there something I am missing? The account using the API is a moderator of the subreddit of what I am trying to update,

Any help would be appreciated.

**Comment by not-an-aardvark** [comment]
What happens if you run `reddit.config({ debug: true})` before those lines?

Are you able to do other things with the subreddit with snoowrap, aside from changing the settings?

Just to make sure, does the subreddit in question actually exist?

**Comment by sambunting** [comment]
Using `reddit.config({ debug: true})` I was able to get the following information:
    
    [debug] Received a 200 status code from a `get` request sent to https://oauth.reddit.com/r/subreddit/about?raw_json=1. ratelimitRemaining: 598
[debug] Received a 404 status code from a `get` request sent to https://oauth.reddit.com/r/subreddit/about/edit?raw_json=1. ratelimitRemaining: 599

The subreddit that I am trying to edit does exist, I am abe to run `reddit.getSubreddit('subreddit').getHot().then(console.log)` and get the front page of the subreddit perfectly fine.

**Comment by not-an-aardvark** [comment]
What scope (permissions on your reddit account) does your access token have? You might have selected these when generating the token.

**Comment by sambunting** [comment]
I'm not using an access token. I am using the wrap which is enabled for bots and automated scripts. I have tried adding `scope: ['modconfig']` to `new Snoowrap()` (I don't think it goes here, but I don't know elsewhere it would) but this just gets me the same error.

**Comment by not-an-aardvark** [comment]
> I am using the wrap which is enabled for bots and automated scripts.

I'm not sure what you mean. Could you clarify how you're authenticating to reddit?

**Comment by sambunting** [comment]
All I am using is:

    const reddit = new snoowrap({
        userAgent: 'useragent',
        clientId: 'clientId',
        clientSecret: 'clientSecret',
        username: 'username',
        password: 'password',
    })

(Values have been changed as they are sensitive information)

From there I can do things like retrieving the hot posts of a subreddit without any issue. Like I said earlier, I tried adding `scope: ['modconfig']` to the options and that did nothing.

**Comment by not-an-aardvark** [comment]
Thanks for providing that info.

When I tried it out myself, I wasn't able to reproduce your issue -- editing the setting works fine for me.

However, when I tried editing the settings on a subreddit that I'm not authorized to change the settings on, I got a 404 error. Could that be the issue? You need to be a moderator of the subreddit, with the `config` permission, to access the subreddit settings.

(I'm not sure why reddit returns a 404 rather than a 403 in this case.)

**Comment by sambunting** [comment]
That was it! The user didn't have the config permission set to them on their account.
