### ISSUE TITLE
WikiPage methods do not work from the browser

### ISSUE THREAD

**Issue by leviroth** [not-an-aardvark/snoowrap#84]
To reproduce: visit https://not-an-aardvark.github.io/snoowrap/, open the console, and paste in the following (with appropriate credentials):

```
const reddit = new snoowrap({
    clientId: 'xxxxxxxx',
    clientSecret: 'xxxxxxx',
    username: 'bjo_test_mod',
    password: 'xxxxxx'
});

const subreddit = reddit.getSubreddit('thirdrealm');
const wikiPage = reddit.getSubreddit('thirdrealm').getWikiPage('index');
wikiPage.fetch();
```

The result is an exception: `OPTIONS https://oauth.reddit.com/r/thirdrealm/wiki/index?raw_json=1 403 ()`. The same thing happened when attempting to edit the wiki page.

I was able to make a submission, so the authentication itself seems to be working fine. Additionally, the code runs fine in Node. The issue seems to be with this specific class, specifically on the browser.

Another user had a similar problem, as documented here: https://www.reddit.com/r/redditdev/comments/6hmhya/snoowrap_browser_409_edit_conflict_when_trying_to/

**Comment by not-an-aardvark** [comment]
Thanks for the report. This is a known reddit API bug: https://github.com/reddit/reddit/issues/1675

There is also a note about this at the top of the [WikiPage](https://not-an-aardvark.github.io/snoowrap/WikiPage.html) docs.
