### ISSUE TITLE
Unwanted behavior with .getRandomSubmission()

### ISSUE THREAD

**Issue by KonradStuewe** [not-an-aardvark/snoowrap#85]
In my code I use the `.getRandomSubmission()` function. When testing it with a little subreddit I created it seemed to not work the way it should. The things that I found out were:

1. When the subreddit only contains post from the user the script is using, it will output an object containing all post of the subreddit.
2. The function simply ignores post from the user that the the script is using. So if the subreddit only contains one post from a different user, it will always pick that one.

Although I can understand why **2.** could make sense in some situations, **1.** really looks like a bug to me that could cause hard to find errors. In case this behavior is wanted it should maybe be noted in the documentations.

btw there is a typo in the example of the [.getRandomSubmission()](https://not-an-aardvark.github.io/snoowrap/Subreddit.html#getRandomSubmission__anchor) function.
It should be
`r.getSubreddit('snoowrap').getRandomSubmission().then(console.log)` and not
`r.getSubreddit('snoowrap').getRandomSubmission.then(console.log)`

**Comment by not-an-aardvark** [comment]
Thanks for reporting. The `getRandomSubmission` function just uses the [`/random` API endpoint](https://www.reddit.com/dev/api#GET_random) under the hood. If it's returning undesirable results sometimes, that's an issue with the reddit API, not with snoowrap.

**Comment by not-an-aardvark** [comment]
Closing because this is not an issue with snoowrap.
