### ISSUE TITLE
snoowrap.fromAuthCode says it requires a clientSecret or access token and returns an error

### ISSUE THREAD

**Issue by ronnyli** [not-an-aardvark/snoowrap#87]
Hi,

I'm successfully receiving a code from `getAuthUrl` but getting an error when passing it to `fromAuthCode`.

Here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/6841011/27563744-74be214e-5aa1-11e7-8cd8-24fd710a54b8.png)

I'm a bit confused by this error since it seems to imply that there isn't an option for creating a snoowrap requester using the authCode. Any tips on where to go from here would be greatly appreciated.

P.S. Here's the code snippet in case I made a silly mistake:
```js
var r = snoowrap.fromAuthCode({
  code: code,
  userAgent: userAgent,
  clientId: clientId,  // the clientId of an "installed app"
  redirectUri: redirectUri
});
```
Thanks!

**Comment by not-an-aardvark** [comment]
Thanks for reporting. This seems like it might be a bug.

What happens if you pass an empty string as the client secret?

```js
var r = snoowrap.fromAuthCode({
  code: code,
  userAgent: userAgent,
  clientId: clientId,
  clientSecret: ''
  redirectUri: redirectUri
});
```

**Comment by ronnyli** [comment]
Thanks for the quick response! Just tried the empty string and got the same error.

**Comment by not-an-aardvark** [comment]
Thanks for checking that.

I just tried it myself, and I think I figured out the issue: When the auth code is valid, snoowrap seems to work as expected, but if something goes wrong in the request, reddit returns a 200 response (with an error object as the body), so snoowrap treats it as success. Then it throws an error internally later on because the response body isn't what it expected.

So I think there are two issues -- your code is invalid for some reason, and snoowrap is handling the error in a confusing way. Is there a chance you're reusing an auth code, or using one significantly later than it was generated? Auth codes can only be used once and expire after a short amount of time (maybe an hour? I'm not sure), so they're not suitable for persistent storage.

**Comment by ronnyli** [comment]
Hm, I generate a new code each time I launch the extension (haven't implemented persistent storage yet) and pass it to `fromAuthCode`. If it helps, another weird error that I see is 'r.getMe is not a function`, which is returned simultaneously with the NoCredentialsError.

Thanks for your time and let me know if there's any way I can provide more helpful info.

![image](https://user-images.githubusercontent.com/6841011/27588407-0278344c-5b16-11e7-906f-ffb25a932d51.png)

Here's the snippet where I generate the auth code right before passing to `fromAuthCode`
```
        var authenticationUrl = snoowrap.getAuthUrl({
          clientId: clientId,
          scope: ['identity', 'submit'],
          redirectUri: redirectUri,
          permanent: false,
          state: 'fe211bebc52eb3da9bef8db6e63104d3' // a random string, this could be validated when the user is redirected back
        });

        var options = {
          'interactive': interactive,
          'url': authenticationUrl
        }
        chrome.identity.launchWebAuthFlow(options, function(redirectUri) {
            ...
            var code = new URL(redirectUri).searchParams.get('code');
            // returned auth code looks legit
            console.log('Snoowrap received code:', code);
            var r = snoowrap.fromAuthCode({
              code: code,
              userAgent: userAgent,
              clientId: clientId,
              redirectUri: redirectUri
            });
            // "r.getMe is not a function"
            r.getMe().then(console.log);
            callback(null, r);
            ...
        });
```

**Comment by ronnyli** [comment]
I created the requester in a callback function and passed the auth code to the callback instead, which worked :+1:
