### ISSUE TITLE
getDuplicates issues invalid requests

### ISSUE THREAD

**Issue by metallicity** [not-an-aardvark/snoowrap#89]
I haven't tested more than a handful of requests, but every call I've tried returns 404, and when I change the _getListing call to use {uri: 'duplicates/' + this.id} in place of {uri: 'duplicates/' + this.name}, it returns a Listing containing all duplicate submissions, as expected.

**Comment by not-an-aardvark** [comment]
Thanks for reporting, this looks like a bug.

It should actually be `this.name.slice(3)`, because the submission might not have been fetched from reddit when the duplicates are fetched, so the `id` property might not be present.

Would you like to submit a PR?

**Comment by metallicity** [comment]
Sure, I went ahead and submitted one, though it's only a one line change.
