### ISSUE TITLE
Proxy config

### ISSUE THREAD

**Issue by danielcooke1996** [not-an-aardvark/snoowrap#91]
I'm having trouble routing all requests through a proxy domain.

Reading through the source code I can see in `request-handler.js` the following example.

```
class AnotherSnoowrapSubclass extends snoowrap {
 rawRequest(options) {
  // send all requests through a proxy
  return request(Object.assign(options, {proxy: 'https://example.com'}))
 }
}

```
But I cannot understand how this specific example should work and I have a few questions:

- It relies on `request-promise` library - how would I retrieve an authorization token using this method?

- Will  I need to make a call to the super (snoowrap) passing in the config object` {userAgent....}` etc, ?

I would suggest allowing a `proxy` property to be specified in the initial object construction.

E.g

```
const otherRequester = new snoowrap({
  userAgent: 'put your user-agent string here',
  clientId: 'put your client id here',
  clientSecret: 'put your client secret here',
  username: 'put your username here',
  password: 'put your password here'

//add property here
proxy: 'optional proxy ip'
});
```

**Edit**: Please note that I'm probably just misunderstanding the use case here - would appreciate any assistance.

**Comment by not-an-aardvark** [comment]
In JavaScript, if no constructor is provided for a subclass, a default constructor is used which calls `super` on all of its arguments. In other words, the example you referenced is equivalent to this:

```js
class AnotherSnoowrapSubclass extends snoowrap {
  constructor(...args) {
    super(...args);
  }
  rawRequest(options) {
    // send all requests through a proxy
    return request(Object.assign(options, {proxy: 'https://example.com'}))
  }
}
```
> I would suggest allowing a `proxy` property to be specified in the initial object construction.

I don't think I'm going to add this because using a proxy is just one of many different preferences that people might have for changing requests. I would rather allow people to customize the request behavior (e.g. by subclassing) so they can make any modifications to it they want, including sending requests through a Proxy.

**Comment by danielcooke1996** [comment]
@not-an-aardvark Thanks for your help. Maybe you would be able to give me some assistance as to why the following is timing out.

```
const snoowrap = require('snoowrap');

class testClass extends snoowrap {
	
	static rawRequest (options) {
		return super.rawRequest(Object.assign(options, {proxy: 'http://192.0.200.246:443'}));
	}
}


const r = new testClass({
	userAgent: 'Node:my-bot-test:1.0.0',
	clientId: 'id',
	clientSecret: 'secret',
	username: 'myusername',
	password: 'mypassword',

	
})


r.oauthRequest({uri: '/user/spez/about', method: 'get'})
	.then(console.log,(err) => console.log(err));
```
