### ISSUE TITLE
Extract title from getNew posts

### ISSUE THREAD

**Issue by skramzy** [not-an-aardvark/snoowrap#94]
How would I get the title of the posts I've pulled into my console from getNew?

r.getSubreddit('testingground4bots').getNew().then(console.log)

**Comment by not-an-aardvark** [comment]
Each post has a `title` property that has the title of the post.

You could do something like

```js
r.getSubreddit('testinggrount4bots').getNew().then(posts => {
  const titles = posts.map(post => post.title);

  // Do something with titles, e.g. print them out
  console.log(titles);
});
```
