### ISSUE TITLE
Compile down to ES5

### ISSUE THREAD

**Issue by ArnaudWeyts** [not-an-aardvark/snoowrap#95]
The production version should be compiled down to ES5.

See [this issue](https://github.com/facebookincubator/create-react-app/issues/2475) for reference.

> `remote: Unexpected token: punc ([) [./~/snoowrap/dist/helpers.js:151,55][static/js/main.e6b3427a.js:1637,56]`

> `return obj && (0, _omit3.default)(_extends({}, obj, { [newKey]: obj[oldKey] }), oldKey);`
In particular, { [newKey]: obj[oldKey] } is ES6. Please ask snoowrap maintainers to compile it down to ES5, and it will work.

**Comment by not-an-aardvark** [comment]
Unfortunately, it's not possible to compile snoowrap down to ES5 because it uses array subclassing.
