### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by c0d3s1ing3r** [not-an-aardvark/snoowrap#97]
Firstly, thanks for making a js wrapper for the reddit API. Makes integrating it a lot easier for node projects.

I'm trying to use snoowrapper to automatically query a subreddit for a random post and then paste the link to that post into a discord that is used by myself and my friends (I'm not using one that already exists as my friends have privacy concerns involving them, furthermore I view it as a good exercise).

I'm using node 7.7.4. Because of the Commando wrapper I'm using, the process isn't exiting and I'm not getting a stacktrace to where the error is.

This is my code:
```
const Commando = require('discord.js-commando')
const snoowrap = require('snoowrap')
const r = new snoowrap({
  userAgent: 'these',
  clientId: 'are',
  clientSecret: 'all-correct',
  refreshToken: 'I-triple-checked-them'
});

class Smug extends Commando.Command{
    constructor(client){
        super(client, {
            name: 'smug',
            group: 'misc',
            memberName: 'smug',
            description: 'Posts a random smug image'
        })
    }

    async run(message, args){
        // line that causes the error:
        post = r.getSubreddit('smuganimegirls').getRandomSubreddit()
        // don't judge me the server is full of weebs
        /* more code that's irrelevant */
    }
}
```

When the user types !smug into chat the console prints: 
```
(node:37248) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'map' of null
(node:37248) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
```
I am unsure if this is because I'm using the package wrong or if there's something wrong with the integration. I'm posting here because I was unable to find people with similar problems.

**Comment by not-an-aardvark** [comment]
The issue is that you're calling the `getRandomSubreddit` method, which doesn't exist. If you're trying to get a random subreddit, I think you can use `r.getSubreddit('random')`. If you're trying to get a random submission, use `r.getSubreddit('your_subreddit').getRandomSubmission().`

**Comment by c0d3s1ing3r** [comment]
I added that to my example code accidentally and edited it to what it was supposed to be.

I reran the code with just r.getSubreddit() and it still returned that error.

**Comment by not-an-aardvark** [comment]
What happens if you run the code with `node --trace-warnings yourFile.js`?

**Comment by c0d3s1ing3r** [comment]
```at CommandMessage.run (G:\Discord Development\flippy\node_modules\discord.js-commando\src\commands\message.js:230:27)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)```

Thanks for teaching me something new about node.

It's apparent the problem wasn't with snoowrap from this though. Sorry for wasting your time.
